examples/dxPtexViewer/dxPtexViewer.cpp, examples/dxPtexViewer/shader.hlsl, opensubdiv/osd/d3d11PtexMipmapTexture.cpp, opensubdiv/osd/hlslPatchBSpline.hlsl, opensubdiv/osd/hlslPatchCommon.hlsl, opensubdiv/osd/hlslPatchGregory.hlsl, opensubdiv/osd/hlslPtexCommon.hlsl
- changed ptex layout data types in shaders to match srv format
- changed ptex srv type to unorm format for uchar data
- fixed hlsl compiler warning: initialized edgeDistance of OutputVertex struct in domain shader even if we are not in wireframe mode
- added directx debug device and enabled automatic break points to easily spot dx errors
before:
after:
=> dxPtexViewer fixes

opensubdiv/osd/glslTransformFeedbackKernel.glsl
- changed loop counter names in addWithWeight and readVertex that have overwritten the outer loop counter due to unrolling
- changed sizes sampler type to match GL_R8UI internal format
The crash occured on an NVidia 780, driver version 347.09, Windows. On Ati everything was fine.
=> Fix for GLTransformFeedback crash in computeStencil

opensubdiv/osd/d3d11ComputeController.cpp, opensubdiv/osd/glslComputeController.cpp
Minor optimization to match the number of needed workgroups to the batch size.
Example: 
```
int workgroupsize = 64; 
int batchSize = 64;
//old:
numDispatches = batchSize/workgroupSize +1;
// = 64/64+1 = 2;
// will start 2 workgroups - 64 threads that have to be setup but will imediately exit
//new:
int numDispatches = (batchSize+workgroupSize-1)/workgroupSize;
// = (64+63)/64 = int(1.98);
// will do what we want and start 1 workgroup
```
=> Optimize GL/DX compute dispatches.

examples/common/clInit.h, opensubdiv/vtr/quadRefinement.cpp, opensubdiv/vtr/triRefinement.cpp, regression/common/CMakeLists.txt, regression/common/cmp_utils.h, regression/common/hbr_utils.h, regression/common/vtr_utils.h, regression/osd_regression/main.cpp, regression/vtr_regression/vtr_regression.cpp
vtr:
- Fixed a potential stack corruption issue with _maxEdgeFaces.
osd_regression:
- I had to disable the loop tests
- I had to disable the hedit tests
- Otherwise everything passes on Linux and Windows with all the existing tested backends (CPU, CPUGL, CL) -- we should add the rest.  (I couldn't test CL on Windows).
- The top-level CMakeLists.txt file still has osd_regression disabled because I haven't yet verified that it compiles on the Mac (it compiles on Windows and Linux).
- I think we should delete far_regression.  It's very outdated and the functionality is covered by vtr_regression.
=> osd_regression test ported over to new API and small bug fix in vtr

examples/glEvalLimit/glEvalLimit.cpp
We were erroneously using the number of vertices of the refined mesh to copy
data only allocated for the coarse mesh's number of vertices.
=> Fixing invalid memory read error in glEvalLimit.

opensubdiv/far/gregoryBasis.cpp
We were incorrectly padding manifoldRing for end boundary vertices.
=> Fix incorrect padding of manifold ring

regression/common/shape_utils.cpp
Fixed a case where we could erroneously fill in the texture or normal index for a vertex on a face when they are not actually specified in the obj.
=> Fixed a bug in our obj parser

examples/dxViewer/dxviewer.cpp
Make sure to initialize the cursor of the window class in dxViewer as required.
=> Fixed a bug in the display of the dxViewer cursor

cmake/FindGLFW.cmake
Previously, FindGLFW would search for both GL/glfw.h and GLFW/glfw3.h, which
does not work when a system has both GLFW 2.0 and 3.0 installed.
The fix still probes for both files, but does so in two passes, preferring
glfw3.h.
=> Fixing FindGLFW cmake module

opensubdiv/osd/glslPatchBSpline.glsl, opensubdiv/osd/glslPatchCommon.glsl, opensubdiv/osd/glslPatchTransition.glsl, opensubdiv/osd/hlslPatchBSpline.hlsl, opensubdiv/osd/hlslPatchCommon.hlsl, opensubdiv/osd/hlslPatchTransition.hlsl
Added a new screen-space adaptive tessellation metric which
computes edge lengths using limit surface points. Made this
the default screen-space metric so that we avoid cracks when
using Gregory Basis or Regular B-spline end caps.
The alternative method which computes edge lengths using the
distance between B-spline control points is still available.
Added a diagram and comments to explain how the control
points and limit points are organized.
=> Limit position screen-space tessellation level metric

opensubdiv/far/ptexIndices.cpp
The only method not yet implemented for loop in PtexIndices is GetAdjacency(), fix code accordingly.
=> Fix ptex indices computations for loop.

opensubdiv/far/patchTablesFactory.cpp, opensubdiv/far/patchTablesFactory.h, opensubdiv/vtr/level.cpp, opensubdiv/vtr/level.h
Now a boundary and corner patch remains
aligned with its underlying parametric
orientation. This simplifies both the
gathering of patch vertices and downstream
evaluation of patches.
Added a method to Vtr::Level which gathers
the 16 patch points for a B-spline patch
even if the patch has boundary or corner
edges.  The undefined patch vertex index
values along boundary and corner edges are
assigned Vtr::INDEX_INVALID.
In order to simplifiy the process of drawing
B-spline patches with boundary or corner
edges, the Far::PatchTablesFactory will
replace any invalid vertex indices with
a known good value, i.e. the index of the
first patch face vertex.
Single-crease patches are still a slightly
special case, which will be resolved later.
=> Fixed orientation of boundary and corner patches

CMakeLists.txt, documentation/cmake_build.rst
- Upped minimum required version of docutils from 0.6 to 0.9.
- Fixed link to pygments in build documentation
- Fixed link to doxygen in build documentation
=> Minor fixes to building docs and doc links.

opensubdiv/far/endCapLegacyGregoryPatchFactory.cpp
Fixed a bad read from a std::vector.  It's normally harmless, but at least makes
debug runtimes cry.
=> Fix an out-of-bounds read.

CMakeLists.txt, examples/common/clDeviceContext.cpp, examples/common/clDeviceContext.h, examples/common/cudaDeviceContext.cpp, examples/common/cudaDeviceContext.h, examples/dxPtexViewer/CMakeLists.txt, examples/dxPtexViewer/dxPtexViewer.cpp, examples/dxViewer/dxviewer.cpp, examples/glImaging/CMakeLists.txt, opensubdiv/osd/CMakeLists.txt, opensubdiv/osd/clD3D11VertexBuffer.cpp, regression/osd_regression/CMakeLists.txt
- resolves DX-CL interop functions in Osd::ClD3D11VertexBuffer.
- enable CL kernels in DX build.
- more cleanup in test harnesses, adding D3D11 initializations into DeviceContext.
- add new defines OPENSUBDIV_HAS_OPENGL for convenience.
=> Fix DX-OpenCL/CUDA interop.

regression/common/shape_utils.h
Shape::isLeftHanded was left uninitialized when Shape is instantiated manually.
=> Fix glPtexViewer backfacing bug: initialize handedness flag in Shape

opensubdiv/vtr/stackBuffer.h
In vtr/stackBuffer.h, removed  unnecessary symbols for parameters to silence
compiler warnings about them not being used.
=> Satisfy compiler warnings about unused parameters.

opensubdiv/osd/clComputeController.cpp, opensubdiv/osd/clKernel.cl, opensubdiv/osd/cpuComputeController.cpp, opensubdiv/osd/cpuKernel.cpp, opensubdiv/osd/cpuKernel.h, opensubdiv/osd/cudaComputeController.cpp, opensubdiv/osd/cudaComputeController.h, opensubdiv/osd/cudaKernel.cu, opensubdiv/osd/d3d11ComputeController.cpp, opensubdiv/osd/glslComputeContext.cpp, opensubdiv/osd/glslComputeController.cpp, opensubdiv/osd/glslComputeKernel.glsl, opensubdiv/osd/glslTransformFeedbackComputeController.cpp, opensubdiv/osd/glslTransformFeedbackKernel.glsl, opensubdiv/osd/hlslComputeKernel.hlsl, opensubdiv/osd/ompComputeController.cpp, opensubdiv/osd/ompKernel.cpp, opensubdiv/osd/ompKernel.h, opensubdiv/osd/tbbComputeController.cpp, opensubdiv/osd/tbbKernel.cpp, opensubdiv/osd/tbbKernel.h
Changing all device kernels to take two buffer identifiers for
source and destination separately.
This change is an intermediate step toward upcoming context/controller
refactoring.
Previously we have a limitation that the source and destination
vertex buffer have to be a single buffer, since the subdivision
tables are iteratively applied level by level.
With stencil tables, we don't have such a limitation any more,
so we may want to apply stencils from a separate source buffer to
another.
To specify the stencil output location within the destination buffer,
we use VertexBufferDescriptor.offset. This allows us not only
configuring arbitrary batching scheme, but also relaxing the
limitation that source and destination buffers had to have a same
interleaved layout. For examples, with this …
=> osd refactor: split the vertex buffer argument into src and dst

examples/dxPtexViewer/dxPtexViewer.cpp, examples/dxViewer/dxviewer.cpp, examples/glPaintTest/glPaintTest.cpp, examples/glPtexViewer/glPtexViewer.cpp, opensubdiv/osd/d3d11DrawContext.cpp, opensubdiv/osd/d3d11DrawContext.h, opensubdiv/osd/d3d11DrawRegistry.h, opensubdiv/osd/mesh.h
- Remove MeshPtexData bit from Osd::MeshBits. It's not used any more
- Rename ptexIndexBuffer in D3D11DrawContext to paramParamBuffer
- Remove Is/SetPtexEnabled from D3D11DrawRegistry
=> cleanup remaining ptex specific code in osd layer

examples/common/patchColors.cpp, examples/common/patchColors.h, examples/dxPtexViewer/dxPtexViewer.cpp, examples/dxViewer/dxviewer.cpp, examples/glFVarViewer/glFVarViewer.cpp, examples/glImaging/glImaging.cpp, examples/glPaintTest/glPaintTest.cpp, examples/glPtexViewer/glPtexViewer.cpp, examples/glShareTopology/glShareTopology.cpp, examples/glViewer/glViewer.cpp, opensubdiv/osd/d3d11DrawContext.cpp, opensubdiv/osd/d3d11DrawContext.h, opensubdiv/osd/d3d11DrawRegistry.cpp, opensubdiv/osd/d3d11DrawRegistry.h, opensubdiv/osd/drawContext.cpp, opensubdiv/osd/drawContext.h, opensubdiv/osd/glDrawContext.cpp, opensubdiv/osd/glDrawContext.h, opensubdiv/osd/glDrawRegistry.cpp, opensubdiv/osd/glDrawRegistry.h, opensubdiv/osd/mesh.h, opensubdiv/osd/tbbKernel.h
Since unified shading work already removed subPatch info from
Osd::PatchDescriptor, the remaining difference between Far::PatchDescriptor and
Osd::PatchDescriptor is just maxValence and numElements. They are used
for legacy gregory patch drawing.
Both maxValence and numElements are actually constant within a topology
(drawContext). This change moves maxValence to DrawContext and let client
manage numElements, then we can eliminate Osd::PatchDescriptor and simply
use Far::PatchDescriptor instead.
This is still an intermediate step toward further DrawRegistry refactoring.
For the time being, adding EffectDesc struct to include maxValence and
numValence to be maintained by the clients. They will be cleaned up later.
The side benefit of this change is we no longer need to recompile regular …
=> Refactor Osd::DrawContext

examples/glEvalLimit/glEvalLimit.cpp, opensubdiv/far/interpolate.cpp, opensubdiv/far/patchParam.h, opensubdiv/far/patchTables.h
My earlier change which simplified the categorization of
patch types broke evaluation for boundary and corner patches.
Previously, boundary and corner patches were always rotated
into a canoncial orientation by permuting the point indices
of the patch. This was convenient in some cases, but generally
made things unnecessarily complicated, since the parameterization
of the patch had to be counter-rotated to compensate.
Now patches always remain correctly oriented with respect
to the underlying surface topology and evaluation of boundary
and corner patches is accommodated by simply adjusting the
spline weights to account for the missing/invalid patch
points along boundary and corner edges.
There is more to clean up and optimize, but this restores
correct behavior.
=> Fixed evaluation of boundary and corner patches

examples/dxViewer/dxviewer.cpp, examples/glViewer/glViewer.cpp, examples/vtrViewer/gl_mesh.cpp, examples/vtrViewer/hbr_refine.cpp, examples/vtrViewer/vtrViewer.cpp, opensubdiv/far/patchDescriptor.cpp, opensubdiv/far/patchDescriptor.h, opensubdiv/far/patchTablesFactory.cpp, opensubdiv/osd/d3d11DrawRegistry.cpp, opensubdiv/osd/glDrawRegistry.cpp
These are now redundant since all bspline patches are encoded in
the patch tables consistently using 16 point indices with boundary
and corner edges indicated in the boundary mask of the patch params.
=> Removed BOUNDARY and CORNER patch types

opensubdiv/far/interpolate.cpp
Fixes a build warning from clang on OS X.
=> Removed an unused local var from interpolate.cpp

examples/dxViewer/dxviewer.cpp
This restores the previous defaults and works around an
apparent runtime error on some platforms which is triggered
in the legacy gregory patch drawing code when patch culling
is disabled.
=> Changed default draw modes for dxViewer

opensubdiv/far/gregoryBasis.cpp
In preparation for raising the maximum valence, this change removes what appears to be the last usage of alloca() that depends on the maximum valence -- replacing it a StackBuffer allocation, which will allocate from the heap if necessary.
=> Removed more usage of alloca() dependent on maximum valence:

examples/glShareTopology/CMakeLists.txt, examples/glShareTopology/glShareTopology.cpp, examples/glShareTopology/init_shapes.h, examples/glShareTopology/meshRefiner.h, examples/glShareTopology/scene.h, examples/glShareTopology/sceneBase.cpp, examples/glShareTopology/sceneBase.h, examples/glShareTopology/shader.glsl, examples/glShareTopology/vbo.h
This example is rewritten as a more comprehensive example
of Far and Osd APIs to generate batched index buffer and
vertex buffer, as well as sharing same topology and stencil
table among multiple objects.
Also this change includes an experimental code path of using
glMultiDrawElementsIndirect. It's currently incomplete due to
the missing interface of osd tessellation shader.
=> update glShareTopology example.

examples/common/CMakeLists.txt, examples/common/d3d11Hud.cpp, examples/common/d3d11Hud.h, examples/common/d3d11Utils.cpp, examples/common/d3d11Utils.h, examples/common/glFramebuffer.cpp, examples/common/glFramebuffer.h, examples/common/glHud.cpp, examples/common/glHud.h, examples/common/glUtils.cpp, examples/common/glUtils.h, examples/dxPtexViewer/dxPtexViewer.cpp, examples/dxViewer/dxviewer.cpp, examples/farViewer/farViewer.cpp, examples/farViewer/gl_fontutils.cpp, examples/farViewer/gl_mesh.cpp, examples/farViewer/gl_mesh.h, examples/glEvalLimit/glEvalLimit.cpp, examples/glFVarViewer/glFVarViewer.cpp, examples/glPaintTest/glPaintTest.cpp, examples/glPtexViewer/glPtexViewer.cpp, examples/glShareTopology/glShareTopology.cpp, examples/glShareTopology/sceneBase.cpp, examples/glStencilViewer/glStencilViewer.cpp, examples/glViewer/glViewer.cpp, opensubdiv/osd/glDrawContext.cpp, opensubdiv/osd/glDrawContext.h
As a preparation for retiring DrawContext, move SupportsAdaptiveTessellation
method to examples/common/glUtils, which is renamed and namespaced
from gl_common.{cpp,h} to be consistent to other files.
Same renamings applied to other example files too.
=> remove SupportsAdaptiveTessellation from OsdDrawContext (and example cleanups)

cmake/FindDXSDK.cmake
The most up-to-date version of the HLSL compiler is now shipped as part
of the Windows SDK. Previously, the HLSL compiler was included with
the DirectX SDK.
There is more that we can do to improve this cmake module, but this
makes it more likely to find the correct tool.
=> Fixed FindDXSDK to prefer more recent D3DCompile

opensubdiv/sdc/catmarkScheme.h, opensubdiv/sdc/loopScheme.h
Just a little more simple loop unrolling and branch reduction for the regular limit masks for Catmark and Loop.  Gathering the limit masks does show up high enough on the profiling radar, so every little bit helps.
=> Minor performance improvements to Sdc limit masks for the regular case:

examples/dxPtexViewer/dxPtexViewer.cpp, examples/dxPtexViewer/shader.hlsl, examples/dxViewer/dxviewer.cpp, examples/dxViewer/shader.hlsl, opensubdiv/osd/CMakeLists.txt, opensubdiv/osd/glslPatchGregory.glsl, opensubdiv/osd/hlslPatchBSpline.hlsl, opensubdiv/osd/hlslPatchCommon.hlsl, opensubdiv/osd/hlslPatchGregoryBasis.hlsl, opensubdiv/osd/hlslPatchShaderSource.cpp
hlslPatchGregoryBasis.hlsl is an equivalent to glslPatchGregoryBasis.
Update dxViewer to be able to switch among bspline, gregorybasis, legacy
end capping.
also fixes a bug of GLSL legacy gregory shader which had an inconsistent
resource naming with example codes.
It looks like there's still an issue of D3D11 patchParam data fetching.
we'll come back to that bug.
=> Add a HLSL version of GregoryBasis patch shader.

opensubdiv/far/endCapGregoryBasisPatchFactory.cpp, opensubdiv/far/gregoryBasis.cpp, opensubdiv/far/gregoryBasis.h
In addition to breaking the friend ship, there was also an unused variable (_offsets) which I removed.
I also wrapped a few lines that looked like they were intended to be 80 chars long, but were slightly longer.
=> Break friendship between GegoryBasis and Factory

examples/dxPtexViewer/dxPtexViewer.cpp, examples/dxViewer/dxviewer.cpp, opensubdiv/osd/glslPatchGregory.glsl, opensubdiv/osd/glslPatchGregoryBasis.glsl, opensubdiv/osd/hlslPatchGregory.hlsl, opensubdiv/osd/hlslPatchGregoryBasis.hlsl
Fix gregory patch tesslevel computation
- flipping UV
- using limit position in legacy gregory shader.
dxViwer/dxPtexViewer enable back-face culling
since we fixed gregory patch rotation/orientation issues.
=> Fix invalid gregory patch tesslevel computation / enable backface culling in DX examples

opensubdiv/far/endCapLegacyGregoryPatchFactory.cpp, opensubdiv/far/endCapLegacyGregoryPatchFactory.h, opensubdiv/far/patchTables.h, opensubdiv/far/patchTablesFactory.cpp
PatchTables no longer needs to friend EndCapLegacyGregoryPatchFactory.
Instead we now make the patch table factory pass in the data that needs
to be updated directly to EndCapLegacyGregoryPatchFactory.
=> Remove need for friending a class in PatchTables.

opensubdiv/far/stencilTablesFactory.cpp
two bugs fixed.
- use patchtables instead of patchTables (yes, quite confusing...) patchtables may be created ondemand if patchTables isn't given as an argument.
- If there's a hole, limit stencils may not be found for the given limit location, resulting invalid stencil entries. Using numLimitStencils to copy resulting stencils fixes that bug.
=> glStencilViewer crash fix

examples/glEvalLimit/glEvalLimit.cpp, opensubdiv/osd/cpuEvaluator.cpp, opensubdiv/osd/cpuEvaluator.h
- it takes number and pointer for the input PatchCoords.
- add derivative evaluations.
- enhance glEvalLimit example to see the derivative evaluation works.
=> implements Osd::CpuEvaluator::EvalPatches function.

examples/glViewer/init_shapes.h, opensubdiv/far/endCapGregoryBasisPatchFactory.cpp, opensubdiv/far/endCapGregoryBasisPatchFactory.h, opensubdiv/far/gregoryBasis.cpp, opensubdiv/far/gregoryBasis.h
Add a non table-based version of end cap tangent computation in gregory basis, and remove MAX_ELEM and MAX_VALENCE limitations.
Also add high-valence regression shapes into glViewer.
note 1: LegacyGregory patch drawing is still under the limitation of maximum valence 29, mostly due to GLSL interstage parameter data width.
note 2: Creating end cap stencils for high-valence shape can be very slow.
=> remove maximum valence limitation in gregory basis and bspline basis end caps.

examples/glViewer/shader.glsl
The output "sharpness" was not being written from the uniform vertex shader, which was causing GLSL compile errors.
I'm not familiar with this code, but zero seems like the correct default value, given the downstream use in the fragment shader.
=> Fix sharpness GLSL error for OSX

opensubdiv/vtr/fvarLevel.h, opensubdiv/vtr/fvarRefinement.h, opensubdiv/vtr/level.h, opensubdiv/vtr/refinement.h
This is a fairly minor change and a precursor to moving all of Vtr into an internal namespace.  For now, all friends have been removed and methods made more accessible.  So no further need to add, remove or rename Far friends within Vtr.  There are now, and should continue to be, no Far references in the Vtr code (other than comments).
=> Removing friends from Vtr classes

opensubdiv/far/stencilBuilder.cpp
Be explicit about the casting from size_t to int in stencilBuilder.cpp.
=> Fix build breakage on MSVC due to implicit downcasting.

opensubdiv/far/stencilBuilder.cpp
Raised as a run-time error by the VS2013 debug STL implementation.
=> Fixed buffer access into empty container

opensubdiv/far/stencilBuilder.cpp, opensubdiv/far/stencilBuilder.h, opensubdiv/far/stencilTableFactory.cpp
Renamed "Internal" namespace to "internal" to match the convention in the rest
of the library.
=> Lower-case Internal namespace to match convention.

opensubdiv/osd/glslComputeKernel.glsl
It looks like there's a compiler bug in some earlier nvidia driver 340/346 releases.
It has been fixed in 348.07 (win) as far as I can tell.
Following code behaves incorrectly.
void f(int a) {
for (int i=0; i<3; ++i) doSomething(a, i);
}
void g() {
for (int i=0; i<100; ++i) f(i);
}
The workaround is to use different identifiers for each function.
=> A workaround for the GLSL compute kernel crash on some nvidia drivers

opensubdiv/far/primvarRefiner.h, opensubdiv/far/topologyLevel.h, opensubdiv/far/topologyRefiner.cpp, opensubdiv/far/topologyRefiner.h, opensubdiv/vtr/refinement.cpp, opensubdiv/vtr/refinement.h
This change set removes the support we added within refinement to propagate the base face of each child face through the refinement hierarchy.  The same -- and more -- can be now be done with the Far::PrimvarRefiner's methods to apply primvar data that is per-face or uniform between levels.  So primvar data can either be directly computed for level, or a set of integers (one per face) can be used to assign the base face to each child face in a level.
Comments and conventions are currently pending for the PrimvarRefiners methods, and the addition follows the existing convention of multi-level methods using ptrs and single-level methods using references -- to be revisited later.
=> Moved base-face propagation to Far::PrimvarRefiner

opensubdiv/far/patchBasis.cpp
Bilinear patches never had appropriate scaling applied to their derivatives to compensate for their depth in the hierarchy.  Hopefully when this low-level basis evaluation is refactored to support more patch types and arbitrary differentiation, this kind of scaling is applied consistently outside the implementation of each basis, not replicated within each.
=> Added missing scaling to derivatives of Bilinear patches

examples/glEvalLimit/glEvalLimit.cpp, examples/glStencilViewer/glStencilViewer.cpp, opensubdiv/osd/clEvaluator.cpp, opensubdiv/osd/clEvaluator.h, opensubdiv/osd/clKernel.cl, opensubdiv/osd/cudaEvaluator.cpp, opensubdiv/osd/cudaEvaluator.h, opensubdiv/osd/d3d11ComputeEvaluator.cpp, opensubdiv/osd/d3d11ComputeEvaluator.h, opensubdiv/osd/glComputeEvaluator.cpp, opensubdiv/osd/glComputeEvaluator.h, opensubdiv/osd/glXFBEvaluator.cpp, opensubdiv/osd/glXFBEvaluator.h, opensubdiv/osd/glslComputeKernel.glsl, opensubdiv/osd/glslXFBKernel.glsl, opensubdiv/osd/mesh.h
implements cuda, CL, GLXFB and GLCompute kernels of derivative
evaluation for both limit stencils and patches.
=> Add GPU stencil/patch derivative kernels

examples/common/glUtils.cpp, examples/common/glUtils.h, examples/glEvalLimit/glEvalLimit.cpp, examples/glPtexViewer/glPtexViewer.cpp, examples/glStencilViewer/glStencilViewer.cpp, examples/glViewer/glViewer.cpp, opensubdiv/osd/clVertexBuffer.cpp, opensubdiv/osd/cpuPatchTable.h, opensubdiv/osd/glslXFBKernel.glsl
- Use unsigned constant in XFB shader
- add GLUtils::GL_ARBComputeShaderOrGL_VERSION_4_3() to see the runtime capability
of GLSL compute kernel for the examples UI
- delete unnecessary include
=> Mac build and shader compiler error fix.

opensubdiv/far/primvarRefiner.h, opensubdiv/far/topologyRefiner.h, opensubdiv/vtr/CMakeLists.txt, opensubdiv/vtr/componentInterfaces.h, opensubdiv/vtr/refinement.cpp
There was no need for the MaskInterface class in vtr/maskInterfaces.h to be defined in Vtr as it never makes use of masks.  There may be more usage in Far in future, but for now it was moved to the Far::PrimvarRefiner which is the only place it is used.
The remaining "interface" classes in Vtr, i.e. those that satisfy the interface of some template parameter, have been moved to vtr/componentInterfaces.h as what is left are interfaces for the mesh components:  vertices, edges and faces.
=> Moved Vtr::MaskInterface into Far::PrimvarRefiner

opensubdiv/far/types.h
far/types.h contains typedef's for equivalence to Vtr::Index but was missing equivalent constants, requiring public use of Vtr::INDEX_INVALID rather than Far::INDEX_INVALID.  Added the missing constants and inline bool Far::IndexIsValid().  Ideally we would have a lower level where these would be defined in future, rather than in Vtr.
=> Added more public constants to <far/types.h>

opensubdiv/far/topologyRefiner.h, opensubdiv/far/topologyRefinerFactory.cpp, opensubdiv/far/topologyRefinerFactory.h, regression/common/vtr_utils.h, tutorials/far/tutorial_1/far_tutorial_1.cpp, tutorials/far/tutorial_1/hbr_to_vtr.h
The suite of base-level modifiers in Far::TopologyRefiner was only used by its Factory, so in the interest of stripping unnecessary baggage from TopologyRefiner they were all moved to its Factory class.  They were added to TopologyRefinerFactoryBase rather than TopologyRefinerFactory<MESH> as they are all independent of the template parameter <MESH>.
Existing Factory<MESH> classes for Shape, Descriptor, etc. were all updated.
=> Moved protected TopologyRefiner modifiers to its Factory class

opensubdiv/far/primvarRefiner.h, opensubdiv/far/stencilBuilder.cpp, opensubdiv/far/stencilBuilder.h, opensubdiv/far/stencilTableFactory.cpp, tutorials/far/tutorial_2/far_tutorial_2.cpp
As decided, we will be relying solely on the AddWithWeight() interface for all forms of primvar data (vertex, varying and face-varying) and eliminating reliance of AddVaryingWithWeight().  Varying data can be interpolated with different methods rather than through a different interface.
I've updated the core code and dependencies and wanted to get that in place as soon as possible.
There are still a number of unused/empty definitions of AddVaryingWithWeight() in some of the examples, tutorials, etc. since it was a requirement.  I will weed out those unused instances in a separate pass.  It looks like the far/tutorial_2 was more devoted to the varying case and warrants more of a rewrite than the simple update here, which I will also follow up on later.
=> Removed primvar interpolation dependency on varying interface

examples/farViewer/farViewer.cpp, examples/glEvalLimit/glEvalLimit.cpp, examples/glShareTopology/sceneBase.cpp, opensubdiv/far/CMakeLists.txt, opensubdiv/far/endCapBSplineBasisPatchFactory.cpp, opensubdiv/far/endCapBSplineBasisPatchFactory.h, opensubdiv/far/endCapGregoryBasisPatchFactory.cpp, opensubdiv/far/endCapGregoryBasisPatchFactory.h, opensubdiv/far/gregoryBasis.cpp, opensubdiv/far/gregoryBasis.h, opensubdiv/far/patchTable.cpp, opensubdiv/far/patchTable.h, opensubdiv/far/patchTableFactory.cpp, opensubdiv/far/stencilTableFactory.cpp, opensubdiv/far/stencilTableFactory.h, opensubdiv/osd/mesh.h, tutorials/far/tutorial_6/far_tutorial_6.cpp
- Fix CMakeLists to move endcap functions into private headers
- add methods into PatchTables to tell the number of patch points needed (GetNumLocalPoints())
and to compute those patch points as a result of change of basis from the refined vertices 
(ComputeLocalPointValues()).
- ComputeLocalPointValues takes contiguous source data of all levels including level0
control vertices.
- remove unnecessary includes from examples.
=> Far: hide endcap factories from public interface

examples/common/glFramebuffer.cpp, examples/common/glUtils.cpp, examples/common/glUtils.h, examples/glViewer/glViewer.cpp
We will need to find a solution for Ignacio's older setup, but this at least
fixes the other fallout.
* Use glewIsSupported instead of glewGetExtension
* Convert tabs to spaces
* Remove GLEW static caching (they only get called once)
* Fix non-const shader string warnings introduced with GL refactoring
=> Fix GLEW for Core profile, minor cleanup

regression/common/cmp_utils.h
Template parameters to local types is only allowed in C++11, instead move the
local type out to an anonymous namespace.
Hopefully fixes #550 / #551 -- @shengfuintel does this fix the ICC compile failure?
=> Fix compile issue for ICC

examples/common/glUtils.cpp, examples/common/glUtils.h, examples/farViewer/farViewer.cpp, examples/glEvalLimit/glEvalLimit.cpp, examples/glFVarViewer/glFVarViewer.cpp, examples/glFVarViewer/shader.glsl, examples/glImaging/glImaging.cpp, examples/glPaintTest/glPaintTest.cpp, examples/glPtexViewer/glPtexViewer.cpp, examples/glShareTopology/glShareTopology.cpp, examples/glStencilViewer/glStencilViewer.cpp, examples/glViewer/glViewer.cpp
The GLFW context version hint is a minimum version, not maximum version so
requesting 4.4 and then falling back to lower versions doesn't make sense.
This change sets the minimum version to 3.2 and attempts to standardize this
across all example apps.
Also print the maximum supported GL version along with the context version
at startup.
=> OpenGL init without errors, example cleanup

examples/common/CMakeLists.txt, examples/dxViewer/CMakeLists.txt
- Make sure to declare usage of the include files if GLFW is found
- When GLFW is found and is compiled into examples/common, we need to
unfortunately link it into dxViewer.  Hopefully we can refactor common
so that this won't be necessary in the future.
=> Fix build breakage due to recent examples/common refactor.

examples/farViewer/farViewer.cpp, examples/mayaPolySmooth/mayaPolySmooth.cpp, opensubdiv/far/primvarRefiner.h, regression/common/vtr_utils.cpp, regression/common/vtr_utils.h, tutorials/far/tutorial_0/far_tutorial_0.cpp, tutorials/far/tutorial_1/far_tutorial_1.cpp, tutorials/far/tutorial_2/far_tutorial_2.cpp, tutorials/far/tutorial_3/far_tutorial_3.cpp, tutorials/far/tutorial_6/far_tutorial_6.cpp
All Interpolate() methods of Far::PrimvarRefiner that iterated over the entire hierarchy have now been removed. These were the ones taking T* and U* that would not work correctly with user-defined types that had overloaded []. All remaining methods should now make consistent use of T&.
Some of the documentation regarding may warrant closer inspection, as well as renaming the template parameters more meaningfully.
Additional minor improvements were made to some of the far/tutorials while replacing the old methods.  far/tutorial_2 in particular was rewritten with a different use case for varying data.
=> Removed multi-level interpolation methods of Far::PrimvarRefiner

examples/mayaPolySmooth/mayaPolySmooth.cpp
Make sure to maintain constness to fix the build break for gcc.
=> Fixed build breakage in mayaPolySmooth.

examples/dxPtexViewer/CMakeLists.txt, examples/dxPtexViewer/dxPtexViewer.cpp, examples/dxViewer/CMakeLists.txt, examples/dxViewer/dxviewer.cpp, examples/farViewer/farViewer.cpp, examples/farViewer/gl_mesh.h, examples/glEvalLimit/glEvalLimit.cpp, examples/glFVarViewer/CMakeLists.txt, examples/glFVarViewer/glFVarViewer.cpp, examples/glImaging/glImaging.cpp, examples/glPaintTest/glPaintTest.cpp, examples/glPtexViewer/glPtexViewer.cpp, examples/glShareTopology/glShareTopology.cpp, examples/glShareTopology/sceneBase.cpp, examples/glStencilViewer/CMakeLists.txt, examples/glStencilViewer/glStencilViewer.cpp, examples/glViewer/CMakeLists.txt, examples/glViewer/glViewer.cpp, regression/common/CMakeLists.txt, regression/common/cmp_utils.h, regression/common/far_utils.cpp, regression/common/far_utils.h, regression/far_regression/far_regression.cpp, regression/osd_regression/main.cpp
- Renamed common/vtr_utils to common/far_utils.
- Renamed all mentions of Vtr in the sources of tests and examples.
=> Remove mention of vtr from tests and examples.

examples/common/glUtils.cpp
It appears the behavior of the version hint is operating system
(and perhaps driver) specific. On OSX the version hint is a
minimum version, but on Linux you get exactly the version
requested.
The GLFW FAQ seems to suggest that any driver not supporting
ARB_compatibility may need the hint.
s
=> Only specify an OpenGL version hint on OSX

opensubdiv/osd/cpuEvaluator.h
When the stencil table contains no stencils, bail out
on the EvalStencil before indexing into the stencil table.
=> Fix out of bounds memory access in CPU stencil eval.

examples/common/glUtils.cpp
Move the core profile specification into the OSX only section.
=> Fix GL context init for Linux and Windows.

examples/farViewer/farViewer.cpp, examples/glPaintTest/glPaintTest.cpp
farViewer and glPaintTest now use GLUtils to set the GL context instead of
rolling their own.
=> Get more viewers using GLUtils.

examples/common/glUtils.cpp, examples/common/glUtils.h, examples/glViewer/glViewer.cpp
Adding command line options to glViewer to make it easy
to control the requested GL version and profile.  While
it is only enabled for glViewer in this change, it will
be easy to extend to all our example viewers.  The new
command line options are:
-glCoreProfile on|off
-glForwardCompat on|off
-glVersion M.n
=> Command line options for GL context.

opensubdiv/osd/glslPatchBSpline.glsl, opensubdiv/osd/glslPatchGregory.glsl, opensubdiv/osd/glslPatchGregoryBasis.glsl
Added a size specifier to the shader output array declaration
in the BSpline control shader. This seems to be required by the
GLSL compiler on AMD and is harmless elsewhere.
=> Workaround GLSL shader compiler on AMD

examples/common/CMakeLists.txt, examples/common/d3d11ControlMeshDisplay.cpp, examples/common/d3d11ControlMeshDisplay.h, examples/common/glControlMeshDisplay.cpp, examples/common/glControlMeshDisplay.h, examples/dxViewer/dxviewer.cpp, examples/dxViewer/init_shapes.h, examples/glEvalLimit/glEvalLimit.cpp, examples/glEvalLimit/particles.cpp, examples/glFVarViewer/glFVarViewer.cpp, examples/glPtexViewer/glPtexViewer.cpp, examples/glStencilViewer/glStencilViewer.cpp, examples/glViewer/glViewer.cpp
- add GLControlMeshDisplay and D3D11ControlMeshDisplay into
examples/common
- delete all drawCageEdges/drawCageVertices from viewers and
use ControlMeshDisplay class
=> Examples cleanup: factor out control mesh drawing.

opensubdiv/far/patchTableFactory.cpp, opensubdiv/far/primvarRefiner.h, opensubdiv/far/topologyRefiner.cpp, opensubdiv/far/topologyRefinerFactory.cpp, opensubdiv/vtr/level.h, opensubdiv/vtr/refinement.h
This is a side-effect of unfriending the Far classes from Vtr -- a few Far classes were directly accessing member variables as friends.  The intent is to appropriately protect members of Vtr classes in the near future, so a few missing accessors were added and the Far classes updated to use them.
=> Eliminated direct member access to Vtr classes from Far

examples/glEvalLimit/particles.cpp, opensubdiv/far/patchParam.h, opensubdiv/far/patchTable.h, opensubdiv/far/patchTableFactory.cpp, opensubdiv/far/topologyRefiner.cpp, opensubdiv/far/topologyRefiner.h, opensubdiv/far/topologyRefinerFactory.cpp, opensubdiv/far/topologyRefinerFactory.h, regression/common/far_utils.h, tutorials/far/tutorial_1/far_tutorial_1.cpp
This set of changes was initially to remove a block of include files from far/TopologyRefiner.h that are now no longer necessary. I looked around at a few other public headers and found a few more that appeared to be unnecessary and removed them as well.
=> Removed unnecessary files include by public headers in Far

opensubdiv/far/patchTableFactory.cpp, opensubdiv/far/topologyLevel.h, opensubdiv/far/topologyRefinerFactory.cpp, opensubdiv/far/topologyRefinerFactory.h, regression/common/far_utils.h, tutorials/far/tutorial_3/far_tutorial_3.cpp
As discussed, I replaced the string FVarFaceValues with FaceFVarValues in a couple of methods in Far -- accessing FVarValues through the TopologyLevel and assigning the base mesh in the RefinerFactory.  I also update the default factory's assignment of face-varying data to be more consistent with the desired terminology.
There is some internal usage in Vtr that still retains the old FVarFaceValue term that I'll deal with soon with some other minor changes to Vtr.
=> Renaming of face-varying methods to access values per face

opensubdiv/vtr/CMakeLists.txt, opensubdiv/vtr/fvarLevel.cpp, opensubdiv/vtr/fvarLevel.h, opensubdiv/vtr/fvarRefinement.cpp, opensubdiv/vtr/fvarRefinement.h, opensubdiv/vtr/level.cpp, opensubdiv/vtr/level.h, opensubdiv/vtr/refinement.h, opensubdiv/vtr/sparseSelector.h
We previously made everything in the Vtr classes public to get rid of all of the Far friends that had been added.  Vtr class members are now appropriately made protected or private, and their friends minimized.  A number of missing accessors were added to prevent direct member access.
The Refinement subclass headers were also added to the private header list (these were the first).
=> Re-protected members of all major Vtr classes

opensubdiv/far/topologyRefiner.cpp
While the feature-adaptive code path is now far more supportive of Loop, its correctness is not assured and there are definitely downstream limitations when it comes to patches.  So until its been more rigorously approved, we're disabling feature-adaptive for anything other than Catmark (which is the state of 2.x).
=> Disabling feature-adaptive refinement for non-Catmark schemes

opensubdiv/far/gregoryBasis.cpp, opensubdiv/far/topologyLevel.h, opensubdiv/far/topologyRefinerFactory.h, opensubdiv/vtr/level.cpp, opensubdiv/vtr/level.h
In keeping with the public change from GetFVarFaceValues() to GetFaceFVarValues(), these changes apply a similar renaming to internal classes that used the same convention.
=> Renamed internal face-varying methods for consistency with public

examples/dxViewer/dxviewer.cpp, examples/dxViewer/shader.hlsl, examples/glViewer/shader.glsl, opensubdiv/far/patchTableFactory.cpp, opensubdiv/osd/glslPatchCommon.glsl, opensubdiv/osd/hlslPatchCommon.hlsl
Use boundaryMask to identify the crease edge from 4 edges, instead of permuting index upfront.
This fix gives consistent patch coordinate on single-crease patches.
In shader, experimentally use the same infinite sharp matrix for both boundary and single-crease
patch. There's still a room for optimization in shader code though.
=> Unlabel rotation of single crease patch.

examples/farViewer/farViewer.cpp, examples/farViewer/gl_mesh.cpp, examples/glFVarViewer/glFVarViewer.cpp, examples/glViewer/glViewer.cpp, opensubdiv/far/patchTable.cpp, opensubdiv/far/patchTable.h, opensubdiv/far/patchTableFactory.cpp
This matches more closely the pattern used elsewhere in Far:
GetFVarPatchValues() --> GetPatchFVarValues()
GetFVarPatchesValues() --> GetFVarValues()
=> Renamed per-patch face-varying access methods

CMakeLists.txt, cmake/FindOpenCL.cmake, examples/common/clDeviceContext.cpp, examples/dxViewer/dxviewer.cpp, opensubdiv/osd/CMakeLists.txt, opensubdiv/osd/clD3D11VertexBuffer.cpp
Build DX/CL interop classes in osd and examples only if cmake finds
cl_d3d11.h or cl_d3d11_ext.h.
Also add some defines to works with both KHR and NV version of extensions.
=> Improve OpenCL/DX interop configuration

examples/farViewer/farViewer.cpp, examples/farViewer/gl_mesh.cpp, opensubdiv/far/patchTable.cpp, opensubdiv/far/patchTable.h, opensubdiv/far/patchTableFactory.cpp, opensubdiv/far/patchTableFactory.h
There's a lot of good foundational work here to eventually support
smooth interpolation of face-varying patches. Unfortunately, this
is not quite ready to release. Therefore, we've decided to defer this
feature until a later release.
This change hides this code behind the FAR_FVAR_SMOOTH_PATCH macro.
=> Prepare to defer face-varying bicubic patches

examples/common/stb_image_write.h, examples/farViewer/farViewer.cpp, opensubdiv/far/patchTableFactory.cpp, opensubdiv/vtr/fvarLevel.cpp
stb - potential use of uninitialized variable (this may have been safe)
farViewer - unused variable
patchTableFactory - _channelIndices potentially used uninitialized
FVarLevel - valueIndexInFace0 potentially used used uninitialized (was safe)
=> Clean up compiler warnings.

examples/farViewer/farViewer.cpp, examples/farViewer/gl_mesh.cpp, opensubdiv/far/patchTable.cpp, opensubdiv/far/patchTable.h, opensubdiv/far/patchTableFactory.cpp
We'll restore this code and finish it up for the next release.
For now, removing this code restores parity with the 3.0 beta,
i.e. face-varying patches are always all bilinear.
=> Removed WIP face-varying bicubic patches

examples/glViewer/init_shapes.h, opensubdiv/far/gregoryBasis.cpp, regression/shapes/all.h, regression/shapes/catmark_gregory_test8.h
Although valence 2 gregory patch is not well supported yet, this fix
mitigates artifacts around such a vertex.
Adding a shape catmark_gregory_test8 to see this issue.
=> Suppress erroneous drawing around valence 2 interior vertex

examples/glEvalLimit/glEvalLimit.cpp, examples/glImaging/glImaging.cpp, examples/glShareTopology/glShareTopology.cpp, examples/glStencilViewer/glStencilViewer.cpp
- Fix crashes on glEvalLimit and glStencilViewer with CLEW
- Currently GPU patch evaluation only supports BSpline patches.
raise an error message in glEvalLimit for the unsupported combinations
until GregoryBasis evaluation will be added to them.
- Add a guard for glMultiDrawElementsIndirect, and also disable it too
=> Examples fixes: clew crash, unsupported GPU evals, MDI

opensubdiv/osd/glslPatchCommon.glsl, opensubdiv/osd/hlslPatchCommon.hlsl
Unified transition patch drawing affects the calculation of
tessellation level metrics. Because a single edge of a shader
patch might be split into two halfs along a transition edge,
the effective maximum number of spans along any adaptive edge
is limited to half of the device maximum.
=> Fixed the tessellation metrics calculations

opensubdiv/far/patchTable.h, opensubdiv/vtr/level.cpp, opensubdiv/vtr/level.h
The use of Class::FVarMethod(..., channel = 0) is convenient for users, but not for internal development.  We've run into a couple of places where the channel argument wasn't properly propagated to another method because of the default value, so I have removed it from internal methods.  In doing so I found one bug that we would have hit with the face-varying patches.
=> Made channel argument non-optional for internal face-varying methods

cmake/FindGLFW.cmake
This is a recently introduced dependency in GLFW 3.1.x
Since Xinerama is widely supported, simply adding this as a required
dependency for now. If this turns out to be a problem then we can
make this dependency optional when using older versions of GLFW.
=> Added Xinerama as a link dependency for GLFW

examples/farViewer/farViewer.cpp
Previously, the farViewer was raising GL invalid operation errors when switching isolation levels.
These resulted from a combination of bad GL calls made to collect query results and to display the control mesh of the current model.
This pull request fixes these two issues and also makes a few changes to the hotkey bindings so that the farViewer is more consistent with the other example viewers.
We may want to consider taking out the performance metric code altogether, since that is not the point of this example.
=> Fixes for farViewer

opensubdiv/far/stencilTable.cpp, opensubdiv/far/stencilTableFactory.cpp
LimitStencilTableFactory::Create was returning fewer number of
stencils, off by the number of coarse vertices.
=> Fix a bug in limit stencil table creation

documentation/release_notes.rst, documentation/roadmap.rst, documentation/subdivision_surfaces.rst
I updated the Roadmap page as discussed to reflect more recent activity and interest.
I also re-ordered some of the topics in the Subdivision Surfaces page to de-emphasize non-manifold topology and some of the other less common features -- given that this is intended as an intro to the topic.  With the non-manifold restrictions now removed, its much less important.
Finally, I re-ordered some of the topics in the Release Notes and did some grouping that warrants review.  Most of the topics seemed to be either Performance or Topology related, so I grouped them as such -- which mainly involved items under Topology since Performance was already evolving that way.  I tried to indent each item so that the item titles stand out more, but had some issues with the RST formatting that I couldn't …
=> More revisions to documentation pages

examples/mayaPolySmooth/CMakeLists.txt
This change fixes a cmake build issue on windows, which fails to create lib
directory when maya example plugin is configured to build.
=> cmake fix: specify the destination file name for the maya script

opensubdiv/vtr/stackBuffer.h
Removed operator[] entirely from StackBuffer to prevent ambiguous overloading error with its TYPE* casting operators.  This is more in keeping with the intended use of StackBuffer as a VLA replacement.
=> Resolve MSVC 32-bit build error with StackBuffer

opensubdiv/far/stencilTableFactory.cpp
If the input cv stencil is given and it includes the local point stencils for endcaps, LimitStencilTableFactory::Create failed because of incorrect sanity checking.
=> Fix a bug in LimitStencilTableFactory

examples/farViewer/farViewer.cpp, examples/glShareTopology/sceneBase.cpp, opensubdiv/far/patchBasis.cpp, opensubdiv/far/patchBasis.h, opensubdiv/far/patchMap.cpp, opensubdiv/far/patchParam.h, opensubdiv/far/patchTable.cpp, opensubdiv/far/patchTableFactory.cpp, opensubdiv/osd/clKernel.cl, opensubdiv/osd/cpuEvaluator.cpp, opensubdiv/osd/cpuPatchTable.cpp, opensubdiv/osd/cudaKernel.cu, opensubdiv/osd/d3d11PatchTable.cpp, opensubdiv/osd/glPatchTable.cpp, opensubdiv/osd/glslComputeKernel.glsl, opensubdiv/osd/glslPatchCommon.glsl, opensubdiv/osd/glslXFBKernel.glsl, opensubdiv/osd/hlslPatchCommon.hlsl, opensubdiv/osd/ompEvaluator.cpp, opensubdiv/osd/tbbKernel.cpp, opensubdiv/osd/types.h
This change restores the use of 4-bits in Far::PatchParam to
encode the refinement level of a patch. This restores one bit
that was stolen to allow for more general encoding of boundary
edge and transition edge masks. In order to accommodate all
of the bits that are required, the transition edge mask bits
are now stored along with the faceId bits.
Also, accessors are now exposed directly as members of Far::PatchParam
and the internal bitfield class is no longer directly exposed.
=> Fixed Far::PatchParam encoding of refinement level

opensubdiv/osd/glLegacyGregoryPatchTable.cpp
Fixed a crash (assertion failure on Windows) that occurs when
creating GLLegacyGregoryPatchTable for a mesh that requires
no Gregory patches.
=> Fixed crash in GL viewers w/ LegacyGregory

opensubdiv/far/topologyDescriptor.h, opensubdiv/far/topologyRefinerFactory.h
The Doxygen page for Far::TopologyRefinerFactory<MESH> had some erroneous mention of specializations for <TopologyDescriptor> and also incorrect ordering of the groups of methods as specified.  The combination made the page almost incomprehensible to a first-time viewer.
=> Doxygen tweaks to prevent it mangling Far::TopologyRefinerFactory<MESH>

documentation/CMakeLists.txt, documentation/compatibility.rst, documentation/nav_template.txt, documentation/porting.rst
The compatibility portions of the "Porting Guide" are now split into a different page.  We'd like to keep
the "Porting Guide" simple and easy to understand.  The Compatiblity portion may live on longer than what is just needed for Porting from 2.x to 3.0.
=> Split out Compatiblity Guide into a separate page.

regression/shapes/catmark_fvar_bound0.h
The intent of regression/shapes/catmark_fvar_bound0 and bound1 was to show the side effects resulting from splitting the lower UV region.  At some point the dart was exaggerated in the bound1 shape but not bound0, so I've corrected bound0 to match.  The documentation will be citing this pair as an illustration of the side effects mentioned (and so a motivation for the new "corners only" mode).
=> Minor revision to one of the regression/shapes

documentation/nav_template.txt
Removed the link to the 'Textures' document because it is incomplete.
Still keep the texture document (in the tree and in the CMakeLists.txt to one day revive.
=> Removed link to incomplete 'Textures' doc.

opensubdiv/vtr/level.cpp
According to issue #648 (closed as it related to another problem) a missing space between literal strings is causing a compilation error with XCode7 on iOS.  This should be a harmless fix.
=> Code tweak to prevent build failure in iOS with XCode7

documentation/compatibility.rst, documentation/intro_30.rst, documentation/release_notes.rst
These changes mainly include the "bottom up" re-ordering we spoke of.  I did some regrouping in the Intro to 3.0 section that warrants a closer look -- most tasks are now grouped into three categories:  "Topology and Refinement", "Limit Properties and Patches" and "Faster Evaluation and Display".  The items in the Release Notes were also updated to be more like one-line descriptions than the subsection titles that they were.
=> Updates to 3.0 Intro and Release Notes docs

documentation/porting.rst
Added a section to the Hbr translation layer about face varying, and a section to the Far layer about the ordering of refined vertices and faces.
Also did a little reformatting -- changed the heading and indentation for the three ways to convert the topology.
=> A few more updates to the Porting Guide

documentation/dxviewer.rst, documentation/far_overview.rst, documentation/osd_overview.rst, documentation/osd_shader_interface.rst
This is a more appropriate (and less jarring) presentation for these notes.
=> Changed most .impnotip doc notes to .notebox

documentation/CMakeLists.txt, documentation/hedits.rst, documentation/nav_template.txt
The Hbr and Hierarchical Edits documents are now clearly marked in a
deprecated section.
=> Moved the Hbr and Hierarchical Edits documents

documentation/far_overview.rst, documentation/nav_template.txt, documentation/porting.rst
Moved big sections out of the porting guide and merged them into
the overview for Far documentation.
=> Simplifying Porting Guide

documentation/intro_30.rst, opensubdiv/osd/glslPatchCommon.glsl
Note that the actual limitation stays same, due to hardware capability
(GL_MAX_VARYING_VECTORS)
=> fix legacy gregory patch shader to support higher valence

documentation/intro_30.rst, documentation/nav_template.txt
Having two introduction sections in the navigation bar was awkward, here I've
left "introduction" as-is but changed "Introduction to 3.0" to "Release 3.0" and
"Release 3.0" to "Overview".
Also some very minor chagnes to the body of intro_30.rst
=> Minor overview doc changes and nav title update

documentation/api_overview.rst, documentation/sdc_overview.rst, documentation/vtr_overview.rst
These changes try and steer users away from spending too much time on the details of Sdc and Vtr.  For most cases they really just need to understand what Sdc is and that they need it for a few simple types and constants -- then they can move to Far.
=> Minor updates to the API overview documentation pages

documentation/subdivision_surfaces.rst
Moved the description of uniform and adaptive refinement to
earlier in the page and also updated the table comparing the
two methods.
Previously, the table contained many restrictions related to
our use of Hbr which no longer need to be considered.
=> Updated subdivision surface intro page

documentation/getting_started.rst
It was the only document that had such a next link.  Also that became no longer true when we put the contributing doc between it and the building doc.
=> Remove the 'Next' link in getting_started.

documentation/porting.rst, documentation/sdc_overview.rst
The changes are mostly limited to punctuation fixes, though some sentences
were restructured for clarity.
The files modified include:
- documentation/porting.rst
- documentation/sdc_overview.rst
=> Added some minor grammar and spelling fixes

examples/farViewer/farViewer.cpp, examples/mayaPolySmooth/mayaPolySmooth.cpp, tutorials/far/tutorial_0/far_tutorial_0.cpp, tutorials/far/tutorial_1/far_tutorial_1.cpp, tutorials/far/tutorial_4/far_tutorial_4.cpp, tutorials/far/tutorial_6/far_tutorial_6.cpp, tutorials/far/tutorial_7/far_tutorial_7.cpp
Far no longer supports this method, so the existing functions were pure noise.
Hbr, however still requires it, so there are still a couple instances of it in
the hbr tutorial files.
=> Remove all unused references to AddVaryingWithWeight

opensubdiv/far/primvarRefiner.h, opensubdiv/far/topologyRefiner.cpp
In one case, we were comparing int and unsigned int.
In primvarRefiner, some values were safely uninitialized, but older compilers
(GCC 4.1) were complaining.
=> Some minor compiler warning fixes

opensubdiv/vtr/fvarLevel.cpp, opensubdiv/vtr/level.h
These changes fix some out range issue I ran into.  
The ones in "level.h" make it so on  windows debug the code does not assert and abort when there are unconnected vertices at the end of the list.
The change in "fvarLevel.cpp" fixes an index out or range when there is face varying data and unconnected vertices.
=> Index out of Range Issues

opensubdiv/osd/ompKernel.cpp
The start index offset was being added twice causing issues when it was non-zero.
=> Fix offsets in OmpEvalStencils when start is non-zero.

opensubdiv/osd/tbbKernel.cpp
The start offset was done twice causing issues when start was non-zero.
=> Fix offsets in TbbEvalStencils when start is non-zero.

opensubdiv/vtr/fvarLevel.cpp, opensubdiv/vtr/level.h, regression/shapes/catmark_nonman_bareverts.h
Vertices in FVar channels were presumed to have at least one incident face.  This lead to some array bounds errors that were recently corrected (#695) but left the vertex uninitialized within the FVar channel.  This change corrects the initialization.
A regression shape with unconnected (bare) vertices was also added for future use.  Like other non-manifold cases, it cannot be included in the far_regression as Hbr will reject it.
Note that unconnected vertices will be implicitly filtered from any feature-adaptive refinement, so these cases are currently only relevant to uniform subdivision.
=> Fixed initialization of unconnected vertices in FVar channels

tutorials/far/tutorial_1/far_tutorial_1.cpp
Seems to be a typo unless i'm mistaken.
=> Fix typo in Far tutorial, GetFaceEdges() actually get face index, not edge index

opensubdiv/far/endCapBSplineBasisPatchFactory.cpp, opensubdiv/far/patchTableFactory.cpp, opensubdiv/far/stencilBuilder.cpp, opensubdiv/far/stencilTableFactory.cpp, opensubdiv/vtr/array.h, opensubdiv/vtr/level.cpp
This is a followup to #698 (merged separately from the pull request) which suppressed a few warnings with ICC.
Some of the pragmas that were added were eliminated through changes to the code.  Those used to suppress legitimate floating-point equality tests were encapsulated in local functions and bracketed with #ifdef __INTEL_COMPILER.
=> Eliminate or encapsulate  recently added ICC pragmas

opensubdiv/osd/cpuPatchTable.cpp, opensubdiv/osd/mesh.h, opensubdiv/osd/types.h, opensubdiv/vtr/quadRefinement.cpp, opensubdiv/vtr/refinement.cpp, opensubdiv/vtr/triRefinement.cpp, regression/common/cmp_utils.h, regression/common/shape_utils.cpp, regression/osd_regression/main.cpp
GCC is far stricter about its symbol shadowing warnings than ICC --for example, being triggered by simple constructors whose argument names match members (a common practice).  They've been reduced in the core libraries and the regression code in this set of changes.  So at least no public headers of the core library will trigger anything if clients turn on -Wshadow.
Unfortunately Hbr triggers a lot of these warnings, so regressions and other examples or tutorials using Hbr will emit a lot of noise if we try to enable -Wshadow by default.
=> Reduced warnings resulting from GCC's -Wshadow option

examples/glEvalLimit/glEvalLimit.cpp, examples/glEvalLimit/init_shapes.h, opensubdiv/far/patchTableFactory.cpp
There's a bug when PatchTableFactory::Options::generateAllLevels is set, resulting
incorrect patch vert indices.
We exclude the vertices of control cage for uniform refinement, even the flag is set.
Note that when we use stencil table and patch table together, they need to be constructed in a consistent way, especially in uniform refinement. If the stencil table includes intermediate levels,
the patch table indexing the vertices generated by the stencil table also takes into account the
number of vertices in the intermediate levels.
The legitimate combinations of uniform refinement are
1. you only need the finest refinement
StencilTableFactory::Options.generateIntermediateLevels = false
PatchTableFactory::Options.generateAllLevels = false
2. you need all levels …
=> Fix a bug in PatchTableFactory of uniform refinement containing all-levels

opensubdiv/far/topologyRefinerFactory.cpp
We mark boundary faces as holes only if the vertex boundary interpolation
is none and the subdivision scheme has local neighborhood to match the prman's behavior.
=> Retains boundary faces of bilinear scheme mesh with VTX_BOUNDARY_NONE

opensubdiv/far/topologyRefinerFactory.cpp
The Far::TopologyRefinerFactory requires a non-zero number of some components on initialization, i.e. the number of vertices and faces.  This had been detected with assertions, which have now been replaced with errors (actually warnings to be consistent with other reporting) allowing the TopologyRefiner creation to simply fail.
=> Replaced topology initialization assertions with errors

examples/common/glHud.cpp, examples/dxViewer/init_shapes.h, examples/glViewer/init_shapes.h
- disable depth test for hud drawing
- remove catmark_pole360 from glViewer/dxViewer
(until we fix the performance issue of high-valence gregory basis patch construction)
=> viewer example fixes

opensubdiv/far/stencilBuilder.cpp, opensubdiv/far/stencilBuilder.h, opensubdiv/far/stencilTableFactory.cpp
Previously, this option flag was being ignored during stencil table
construction. This change now respects the flag.
Fixes issue #694
=> Respect factorizeIntermediatLevels option

opensubdiv/far/error.cpp, opensubdiv/far/error.h, opensubdiv/far/primvarRefiner.h, opensubdiv/far/ptexIndices.cpp, opensubdiv/far/topologyRefiner.cpp, opensubdiv/far/topologyRefinerFactory.cpp, opensubdiv/far/topologyRefinerFactory.h
This change includes updates to Error() calls in Far so that their message strings are consistent.  All strings now include a specific (public) method within which the error originated along with its cause.
Minor changes to the formatting of the default message handlers were also made based on offline discussions.
=> Minor content and formatting changes to Far error strings

opensubdiv/far/topologyRefinerFactory.h, opensubdiv/osd/mesh.h
This pull request contains fixes which we needed to apply on the sources in order to make OpenSubdiv linking finely with Blender. Using gcc 4.9 on Linux and MSVC 2013 on Windows.
This is so called "works for us" and extra checks on whether it causes regressions for someone wouldn't hurt.
=> Fixing linking errors on both Linux and WIndows

CMakeLists.txt, examples/common/CMakeLists.txt, opensubdiv/CMakeLists.txt, opensubdiv/osd/CMakeLists.txt
Changes to the cmake projects so that if all the gpu options are disabled it does not try to make the gpu library.  Also made it so GLFW is not required if NO_OPENGL is specified.
Not sure if this was the best way to do this, but it seemed that the gpu build should not be required if the NO_* options don't require a gpu library.
=> Fixes cmake projects for non-gpu use case

examples/glImaging/glImaging.cpp, examples/glImaging/shader.glsl, opensubdiv/vtr/level.cpp
This fixes a regression in the function used to identify single crease
patches. This also updates the patch color values used by the glImaging
regression test to match the colors used in other example viewers so
that patch types can be more easily identified during automated testing.
=> Fixed single crease patch classification

opensubdiv/osd/glComputeEvaluator.cpp
GLSL programs used by stencil and patch kernels were freed from
both GLSL Compute Evaluator and from kernel classes themselves.
=> Fix GLSL program being deleted twice in GLSL Compute controller

examples/common/clDeviceContext.cpp, examples/common/cudaDeviceContext.cpp, opensubdiv/osd/opengl.h
Misspelled W32_LEAN_AND_MEAN in osd/opengl.h had no effect on windows.h.
Also added to example code wherever windows.h is included.
=> use WIN32_LEAN_AND_MEAN properly

opensubdiv/far/endCapBSplineBasisPatchFactory.cpp, opensubdiv/far/endCapBSplineBasisPatchFactory.h, opensubdiv/far/endCapGregoryBasisPatchFactory.cpp, opensubdiv/far/gregoryBasis.cpp, opensubdiv/far/gregoryBasis.h
In 3.0.2, both gregory basis and bspline endcap construction are very slow, due to the stencil computation on std::vector. We have a plan for more fundamental refactoring in the future release though, this change mitigate most of the performance issue until then.
- replace the std::vectors with vtr::StackBuffer.
- optimize limit stencil computations for GregoryBasis evaluation.
- add a more efficient BSpline endcap generation path.
=> optimize PatchTableFactory::Create performance

opensubdiv/osd/glPatchTable.cpp
Also use GL_ARRAY_BUFFER for the binding point of updating indices instead of GL_ELEMENT_ARRAY_BUFFER
=> Removing debug code that mistakenly slipped into glPatchTable.cpp.

opensubdiv/osd/glslComputeKernel.glsl
Fixes #735, corrupted mesh issues with GLSL Compute on AMD platforms.
=> Set layout to std430 for GLSL Compute kernel

opensubdiv/far/patchTableFactory.cpp
Patches around non-manifold vertices are currently approximated with regular patches, which works well in some cases but not all.  Ultimately we need irregular patches (or at least some kind of extrapolated regular patch) to represent these without cracks, which is planned for the future.
Until then, this change uses regular corner patches around non-manifold vertices that are sharpened to interpolate the vertex and reduce cracks between the patches around it.  This does not eliminate cracks with the adjacent interior patches, but it is hoped the isolation level is deep enough to make them negligible until the longer term solution is in place.
=> Improved patch approximations around non-manifold features

opensubdiv/far/endCapBSplineBasisPatchFactory.cpp, opensubdiv/far/endCapBSplineBasisPatchFactory.h, opensubdiv/far/endCapGregoryBasisPatchFactory.cpp, opensubdiv/far/endCapGregoryBasisPatchFactory.h, opensubdiv/far/gregoryBasis.cpp, opensubdiv/far/gregoryBasis.h, opensubdiv/far/patchTableFactory.cpp, opensubdiv/far/stencilTable.h
- instead of accumulating GregoryBasis::Point (fixed size stencils
backed by stackbuffer), pack the stencils into StencilTable as they
are evaluated
- use single integer for varying stencils of patch points, not
a GregoryBasis::Point
- cap the reserved stencil entry size.
=> Reduce the transient memory consumption in endcap construction.

opensubdiv/far/stencilTable.h
Now Far::LimitStencilTable provides proper accessor
methods for retrieving individual LimitStencils from
the table.
=> Added missing LimitStencil accessor methods

opensubdiv/osd/glslPatchCommon.glsl, opensubdiv/osd/hlslPatchCommon.hlsl
For now, the common patch shader code supports fractional spacing
modes only when screen-space tessellation is also enabled.
It's possible to relax this restriction, but that requires changing
the client shader interface.
=> Disabled fractional spacing w/o screen space tess

opensubdiv/far/stencilTableFactory.cpp
Now StencilTableFactory::AppendLocalPointStencilTable() does
nothing when the localPointStencilTable is empty. This avoids
a potential crash (failed assertion) when both the baseStencilTable
and the localPointStencilTable are empty, as is the case for
simple geometry like the all-quads torus regression test shape.
=> Fixed potential crash in Far::StencilTableFactory

opensubdiv/far/patchTableFactory.cpp
My previous fix added some defensive logic in case the
local point stencil table was empty when attempting to
append local point stencils to an existing stencil table.
This change fixes Far::PatchTableFactory to not return
empty local point stencil tables when there are no local
point stencils. This behavior is now more consistent with
earlier releases.
We will leave the earlier defensive logic in place as well.
=> Improved fix for stencil table construction

opensubdiv/osd/clEvaluator.cpp, opensubdiv/osd/clEvaluator.h, opensubdiv/osd/clVertexBuffer.cpp, opensubdiv/osd/clVertexBuffer.h
Allow giving the start events and returning the end event when updating and evaluating the vertex buffer. So it will be more flexible to do synchronization for parallel execution of multiple CL kernels.
If no event is given, the methods will behave the same as before.
=> Add events control to clVertexBuffer and clEvaluator

opensubdiv/osd/glslPatchCommon.glsl, opensubdiv/osd/hlslPatchCommon.hlsl
These changes help improve the measured performance of the
GL tessellation control shader code and mitigate some performance
regressions we've seen since v3_0_0_RC1
Equivalent changes have been made to both the GLSL and HLSL
code paths. Performance is improved somewhat on DX11 but the
differences there are much less than GL.
=> Tess shader performance fix

examples/common/glslPtexCommon.glsl, examples/common/hlslPtexCommon.hlsl
with MSAA enabled, patchcoord could overrun the guttering pixels.
=> fix ptex lookup shaders to clamp the patchcoord

opensubdiv/far/patchTableFactory.cpp, opensubdiv/far/stencilTable.h
An earlier change improved transient memory usage during the construction
of end cap stencil tables but could leave unused capacity in the internal
containers of the resulting tables. This change adds an additional
internal factory helper method which trims this storage.
=> Fixed residual memory consumed by end cap stencils

CMakeLists.txt, cmake/FindPTex.cmake, examples/CMakeLists.txt, examples/common/d3d11PtexMipmapTexture.cpp, examples/common/d3d11PtexMipmapTexture.h, examples/common/glPtexMipmapTexture.cpp, examples/common/glPtexMipmapTexture.h, examples/common/ptexMipmapTextureLoader.cpp, examples/common/ptexMipmapTextureLoader.h, examples/dxPtexViewer/CMakeLists.txt, examples/dxPtexViewer/dxPtexViewer.cpp, examples/dxPtexViewer/shader.hlsl, examples/dxPtexViewer/sky.cpp, examples/dxPtexViewer/sky.h, examples/dxPtexViewer/skyshader.hlsl, examples/glPtexViewer/CMakeLists.txt
- fix build compiling & linking to accomodate recent code churn in Ptex
- fix FindPTex.cmake module to correctly extract version number
- fix dxPtexViewer & glPtexViewer source to compile with new Ptex namespace changes
- add alpha channel padding function to ptexMipmapLoader as a workaround to the absence of 3-channel DXGI formats
- mirror ptex memory limit function from glPtexViewer to dxPtexViewer
Sorry - the previous PR was messed up : hopefully this will work better...
=> Ptex fixes:

opensubdiv/sdc/crease.cpp
This pull request addresses issue #789.
The bug occurs using the Chaikin crease method when a vertex transitions from Corner to Crease with infinitely sharp edges.  When no semi-sharp edges are present around a vertex, all child sharpness values should be inherited from their parent -- both smooth and infinitely sharp -- and not all presumed smooth.
=> Fixed Chaikin-related bug causing crashes in debug for MSVC and others

regression/common/far_utils.h, regression/common/hbr_utils.h, regression/far_regression/far_regression.cpp, regression/far_regression/init_shapes.h
The changes included here are intended to give far_regression more direct control of each Shape object so that it can make appropriate decision based on content, potentially modify the Shape before execution, etc.  Global functions in regression/common were overloaded to take a pre-existing Shape object instead of the shape string to be parsed.  Only additions were made to the interface of regression/common, no changes to any function signatures.
While the intent here was to facilitate future extensions, the immediate effect on far_regression is as follows -- it will now:
- load all regression shapes, not a subset based on assumptions of their content
- refine all regression shapes with Far
- inspect features of each shape for compatibility with Hbr and skip any deemed incompatible
- …
=> Improvements to far_regression

examples/common/d3d11ShaderCache.cpp, examples/common/hud.cpp, examples/common/hud.h, examples/common/objAnim.cpp, examples/dxViewer/dxviewer.cpp, opensubdiv/far/stencilTable.h, opensubdiv/osd/mesh.h, tutorials/far/tutorial_3/far_tutorial_3.cpp, tutorials/far/tutorial_8/far_tutorial_8.cpp, tutorials/hbr/tutorial_1/hbr_tutorial_1.cpp, tutorials/hbr/tutorial_2/hbr_tutorial_2.cpp
Renaming `and`, `or`, and `not` et. al for the DirectX project. Ref 779.
=> iso-646 fix for DirectX project

CMakeLists.txt
Now that all of the code changes have been integrated
we can remove the alternative keyword defines from
the MSVC build.
Fixes #779
=> iso-646 fix remove obsolete compiler defines

CMakeLists.txt, documentation/CMakeLists.txt, examples/mayaPolySmooth/CMakeLists.txt
As mentioned in issue #814, avoiding the use of CMAKE_SOURCE_DIR makes it easier to integrate OpenSubdiv as a submodule in other projects.
Fixes #814.
=> No longer use CMAKE_SOURCE_DIR and CMAKE_BINARY_DIR

opensubdiv/far/endCapBSplineBasisPatchFactory.cpp, opensubdiv/far/endCapBSplineBasisPatchFactory.h, opensubdiv/far/endCapGregoryBasisPatchFactory.cpp, opensubdiv/far/endCapGregoryBasisPatchFactory.h, opensubdiv/far/gregoryBasis.cpp, opensubdiv/far/gregoryBasis.h, opensubdiv/far/patchTableFactory.cpp, opensubdiv/vtr/level.cpp, opensubdiv/vtr/level.h
With ongoing work to identify patches around discontinuities such as face-varying boundaries or infinitely sharp creases, its useful to have a consistent representation of a sub-ring around a vertex.  The VSpan in Vtr::Level provides that along with a gathering method in Vtr::Level.  It is a simple and compact pair of local indices that identify the origin and extent of a set of faces around a vertex.
This is still work in progress but after offline discussions we wanted to make it available for development that's currently ongoing.  Aside from the definition and gathering method in Vtr, this set of changes includes extensions of signatures to several Far patch construction methods to accept a set of VSpan[4] for the four corners of a patch.
Aside from the plumbing to move the VSpan …
=> Introducing Vtr::Level::VSpan to standardize representation of partial rings around vertices

opensubdiv/far/patchTableFactory.cpp
The bug appears to be the result of a cut/paste oversight -- when populating the irregular patch types, the sharpness index vector that was used was that of the regular patches rather than the specific patch type.
This doesn't appear as a problem now because the corruption of the regular vector only occurs in the last level when Gregory patches are generated, and single crease patches are not generated in the last level.  Once Gregory patches are generated before the last level, the corruption of single crease patches becomes evident.
=> Fixed bug in Far::PatchTableFactory to correct sharpness assignment:

opensubdiv/far/patchBasis.cpp, opensubdiv/far/patchBasis.h, opensubdiv/far/patchTable.cpp, opensubdiv/far/patchTable.h, opensubdiv/far/stencilBuilder.cpp, opensubdiv/far/stencilBuilder.h, opensubdiv/far/stencilTable.cpp, opensubdiv/far/stencilTable.h, opensubdiv/far/stencilTableFactory.cpp, opensubdiv/far/stencilTableFactory.h, opensubdiv/far/topologyLevel.h, opensubdiv/vtr/types.h, regression/common/far_utils.h
When doing cloth simulations the 2nd partials are needed to describe the curvature.
=> Teach the LimitStencilTable to compute 2nd partial derivatives

opensubdiv/far/endCapGregoryBasisPatchFactory.cpp, opensubdiv/far/endCapGregoryBasisPatchFactory.h, opensubdiv/far/patchTableFactory.cpp, opensubdiv/far/topologyRefiner.cpp, opensubdiv/far/topologyRefiner.h
This change includes internal support allowing different levels of adaptive refinement for extra-ordinary vertices vs other sharp features -- preventing the over-representation of smooth patches around all extra-ordinary vertices when a high level of refinement is required for a particular crease.
The feature is not publicly exposed here yet (we need to work out some public interface details) but removes internal assumptions when constructing patches that irregular patches can only exist at the last level of refinement.  Any further changes in this area should now be constrained to the refinement stage rather than patch construction.  Changes to adaptive refinement here are minor but due to change more extensively soon to better support infinitely sharp creases.
=> Add internal support for separate levels of refinement for different features

opensubdiv/far/patchTable.cpp, opensubdiv/far/patchTable.h, opensubdiv/far/patchTableFactory.cpp
This change updates Far::PatchTable to include support for
evaluating varying and face-varying data on patches.
This adds to existing API and follows the existing patterns
used for vertex patches.
This includes data and methods to evaluate varying and
face-varying basis functions as well as methods to compute
local point values for varying and face-varying primvar data.
This is the foundation for updating Far::PatchTableFactory
to generate bicubic patches for face-varying channels.
=> Updated PatchTable for Varying and Face-Varying

opensubdiv/far/topologyRefinerFactory.cpp, opensubdiv/vtr/level.cpp, opensubdiv/vtr/level.h, opensubdiv/vtr/refinement.cpp
As a basis for upcoming work to improve patches around infinitely sharp features, this change includes the definition and propagation of new vertex tags that identify the presence and nature of infinitely sharp features at a vertex.  As with other VTags, this greatly simplifies the logic required in adaptive refinement and patch construction.  The new tags are not yet used to affect adaptive refinement or patches -- they are only defined, initialized and propagated through the refinement hierarchy, making them available for these processes in future.
=> Added new vertex tags to identify infinitely sharp features

opensubdiv/far/endCapBSplineBasisPatchFactory.cpp, opensubdiv/far/endCapBSplineBasisPatchFactory.h, opensubdiv/far/endCapGregoryBasisPatchFactory.cpp, opensubdiv/far/endCapGregoryBasisPatchFactory.h, opensubdiv/far/endCapLegacyGregoryPatchFactory.cpp, opensubdiv/far/endCapLegacyGregoryPatchFactory.h, opensubdiv/far/patchTableFactory.cpp, opensubdiv/far/patchTableFactory.h
Re-organized the implementation of the patch table factory
in advance of adding support for bicubic face-varying patches.
- Renamed the AdaptiveContext internal class to BuilderContext
since this can be used (eventually) to build patch tables for
uniformly refined topology as well as adaptively refined
topology.
- Added utility methods to gather patch vertices from the
levels (and eventually fvarLevels) of a refiner.
- Replaced the FVarChannelCursor with a simpler array of integer
face-varying channel indices.
- Extracted the topology inspection needed to identify
patches into a computePatchTag() method.
- Simplified the two-pass traversal of the topology into a
single pass traversal of the refined topology followed by
an iteration over the patches that have been identified.
- Replaced …
=> Refactored Far::PatchTableFactory

opensubdiv/far/patchTableFactory.cpp
The case where refinement produces no regular
patches was not being accounted for correctly.
Also, fixed the spelling of PatchTupleVector.
=> Fixed packing of regular patches

opensubdiv/far/endCapBSplineBasisPatchFactory.cpp, opensubdiv/far/endCapBSplineBasisPatchFactory.h, opensubdiv/far/endCapGregoryBasisPatchFactory.cpp, opensubdiv/far/endCapGregoryBasisPatchFactory.h, opensubdiv/far/endCapLegacyGregoryPatchFactory.cpp, opensubdiv/far/endCapLegacyGregoryPatchFactory.h, opensubdiv/far/patchTableFactory.cpp
Added support for gathering face-varying patch points to
the Far::EndCap*PatchFactory classes. Also, changed these classes
to compute varying stencils optionally, since separate varying
stencils are not needed for face-varying patches.
Also, removed a no longer used stateless factory method from
the EndCapGregoryBasisPatchFactory.
=> Updated Far::EndCap*PatchFactory for fvar patches

opensubdiv/far/gregoryBasis.cpp, opensubdiv/far/gregoryBasis.h
These changes re-organize and improve documentation for the main conversion of irregular patches to Gregory form.  Obsolete and unused code in the related Far::GregoryBasis and ProtoBasis classes was also removed.
=> Clean up Gregory patch conversion in preparation for future work

opensubdiv/far/patchTable.cpp, opensubdiv/far/patchTable.h, opensubdiv/far/patchTableFactory.cpp, opensubdiv/far/patchTableFactory.h
In order to support a consistent API for refinement and
evaluation of varying primvar data, Far::PatchTable needs
to provide indices for varying data. This adds support to
Far::PatchTableFactory for generating these indices.
=> Populate varying vertices in Far::PatchTable

opensubdiv/far/patchBasis.cpp, opensubdiv/far/patchBasis.h, opensubdiv/far/patchParam.h, opensubdiv/far/patchTable.cpp, opensubdiv/far/patchTable.h, opensubdiv/far/patchTableFactory.cpp, opensubdiv/far/patchTableFactory.h, opensubdiv/osd/cpuEvaluator.cpp, opensubdiv/osd/ompEvaluator.cpp, opensubdiv/osd/tbbKernel.cpp
Improved documentation for Far::PatchParam and
refactored the implementation to allow better reuse
for evaluating patches from face-varying channels.
These changes preserve backward source compatibility
with the public APIs.
=> Refactored Far::PatchParam

opensubdiv/far/endCapBSplineBasisPatchFactory.cpp, opensubdiv/far/patchBasis.cpp, opensubdiv/far/patchBasis.h, opensubdiv/far/patchParam.h, opensubdiv/far/patchTable.cpp, opensubdiv/far/patchTable.h, opensubdiv/far/patchTableFactory.cpp, opensubdiv/far/patchTableFactory.h, opensubdiv/far/topologyRefiner.cpp, opensubdiv/osd/cpuEvaluator.cpp, opensubdiv/osd/ompEvaluator.cpp, opensubdiv/osd/tbbKernel.cpp
These changes add basic support for building patch
tables with smooth face-varying patches. There is more
work to do to improve topological inspection and
tagging in order to take full advantage of improvements
for handling the change of basis for irregular patches.
=> PatchTableFactory changes for smooth FVar patches

opensubdiv/far/patchParam.h, opensubdiv/far/patchTable.cpp, opensubdiv/far/patchTableFactory.cpp
The patches generated for a face-varying channel can be a
mix of regular patches and patches in an alternate basis
for faces that are irregular in face-varying space.
This mix of patches is packed into a single fvar value array
in the patch table using a consistent stride with the individual
patch type determined by the fvar patch param encoding.
- Added Far::PatchParamBase::IsRegular() to designate which
patches are regular.
- Updated Far::PatchTableFactory to gather mixed basis
patches when using the Gregory basis approximation for
irregular patches.
- Fixed Far::PatchTable::EvaluateBasisFaceVarying() to
use the fvar patch param encoding to determine the type
of face-varying patches.
=> Improved PatchTableFactory for mixed FVar patches

opensubdiv/far/patchTableFactory.cpp, opensubdiv/far/patchTableFactory.h, opensubdiv/vtr/fvarLevel.cpp, opensubdiv/vtr/fvarLevel.h, opensubdiv/vtr/level.cpp, opensubdiv/vtr/level.h
These changes reorganize some of the work in Far::PatchTableFactory to simplify the recognition and construction of patches for face-varying channels. Patches are now more clearly separated into regular and irregular patches, with the recognition and inspection of regular patches streamlined.
The construction of face-varying patches now reuses information gathered from the vertex patch when the face-varying topology locally matches. This will help synchronize the vertex and face-varying patches when other topological decisions are made, e.g. when we enable infinitely sharp patches.
=> PatchTableFactory improvements for face-varying patches

opensubdiv/far/endCapGregoryBasisPatchFactory.cpp, opensubdiv/far/patchTableFactory.cpp
Sharing of points for adjacent face-varying Gregory patches had been disabled as edges that were discontinuous in face-varying space were not being detected in the Gregory patch factory.  The Gregory patch factory now detects such edges and the sharing option has been re-enabled in the PatchTableFactory.
=> Enabled point sharing for face-varying Gregory patches

opensubdiv/far/topologyRefiner.cpp, opensubdiv/far/topologyRefinerFactory.cpp, opensubdiv/vtr/fvarLevel.cpp, opensubdiv/vtr/fvarLevel.h, opensubdiv/vtr/level.cpp, opensubdiv/vtr/level.h
This change set includes some cleanup and minor extensions to the tags that are used to accelerate topology inspection.  Some obsolete/redundant tags were removed along with some awkward methods formerly used for their inspection.  Recent additions now provide a more consistent interface for gathering the tags for both vertex and face-varying topology.
=> Minor updates to tags for face-varying and inf-sharp topology

opensubdiv/far/endCapBSplineBasisPatchFactory.cpp, opensubdiv/far/gregoryBasis.cpp, opensubdiv/far/patchTableFactory.cpp, opensubdiv/vtr/fvarLevel.cpp, opensubdiv/vtr/fvarLevel.h, opensubdiv/vtr/level.cpp, opensubdiv/vtr/level.h
These are minor changes to better support non-manifold cases in future, but are being pushed now to update usage and verify correctness in more common cases.
The "leading edge" member of Vtr::Level::VSpan turns out to be ambiguous when the vertex is non-manifold as the face that follows may not be clearly defined if that edge is non-manifold -- changing the start of the span to identify a face will be unambiguous.  A "partial ring" may also be periodic in non-manifold cases (e.g. the apex of a double cone, which has two separate periodic spans) so additional members were added.  Some simple convenience members were add now that this struct is getting more complex.
Also renamed members of the face-varying span (Vtr::FVarLevel::ValueSpan) to better reflect usage, and moved its definition …
=> Improved internal span types for support non-manifold cases

opensubdiv/far/topologyRefiner.cpp, opensubdiv/far/topologyRefiner.h
The motivation for this change was the addition of a new adaptive refinement feature to stop isolation of inf-sharp patches when they are detected as regular.  Given other recent changes to adaptive refinement (separate isolation levels), the need to support backward compatible behaviour, the addition of new tags to simplify selection, etc., it was time to refactor the adaptive refinement code to more easily support current and future features.
The core face selection code was extracted and greatly simplified using new tags that had been previously added to support inf-sharp feature recognition.  Even if not using inf-sharp patches, these tags exist and greatly simplify the recognition of regular boundaries.  The selection code for face-varying channels was also extracted into a separate …
=> Extended adaptive refinement for inf-sharp patches and simplified

opensubdiv/far/topologyRefiner.cpp, opensubdiv/far/topologyRefiner.h
This change exposes controls for adaptive refinement for face-varying patches and inf-sharp patches that have been internalized to this point.  It also includes the secondary isolation level to reduce excessive refinement of smooth vs semi-sharp features.
=> Added new options for adaptive refinement

opensubdiv/vtr/fvarLevel.cpp
This change corrects a regression that was introduced when face-varying inspection was switched to use the new tags for inf-sharp features, resulting in incorrect refinement for some face-varying patches.  It was most noticeable in the "linear boundaries" case as sharp boundaries were not being correctly identified.
=> Fixed topology tagging bug affecting face-varying patches

opensubdiv/far/stencilBuilder.cpp, opensubdiv/far/stencilBuilder.h, opensubdiv/far/stencilTable.cpp, opensubdiv/far/stencilTable.h, opensubdiv/far/stencilTableFactory.cpp, opensubdiv/far/stencilTableFactory.h
This change updates the Far::LimitStencilFactory to
to support options to generate 1st and 2nd derivative
limit stencil weights.
For backward compatibility, the option to generate 1st
derivatives defaults to true.  While for efficiency,
the option to generate 2nd derivatives defaults to false.
Also, updated the Far::LimitStencil class to expose
computed 1st and 2nd derivative limit stencil weights.
=> Added Derivative Options to LimitStencilFactory

opensubdiv/far/patchBasis.cpp, opensubdiv/far/patchBasis.h, opensubdiv/far/patchParam.h, opensubdiv/far/patchTable.cpp, opensubdiv/far/patchTable.h, opensubdiv/far/patchTableFactory.cpp, opensubdiv/osd/cpuEvaluator.cpp, opensubdiv/osd/ompEvaluator.cpp, opensubdiv/osd/tbbKernel.cpp
This reverts most of the recent changes to the
organization of Far::PatchParam. In particular,
the core parameterization is no longer exposed
as a speparate PatchParamBase class.
We'll revisit this again in a later release, but
for now we will stick with a more straight
forward implementation.
=> Reverted recent Far::PatchParam refactoring

opensubdiv/far/patchBasis.cpp, opensubdiv/far/patchBasis.h, opensubdiv/far/patchDescriptor.h, opensubdiv/far/patchParam.h, opensubdiv/far/patchTable.cpp, opensubdiv/far/patchTable.h, opensubdiv/far/patchTableFactory.cpp, opensubdiv/osd/cpuEvaluator.cpp, opensubdiv/osd/ompEvaluator.cpp, opensubdiv/osd/tbbKernel.cpp
Removed bitfield size from Far::PatchDescriptor
This was an obsolete relic from when PatchDescriptor
was more than a single enum value, but it can cause
problems when sharing patch descriptor values between
devices.
Also, marked the GetNumFVarControlVertices() method as
deprecated.
=> Removed bitfield size from Far::PatchDescriptor

opensubdiv/far/patchBasis.cpp, opensubdiv/far/patchBasis.h, opensubdiv/far/patchDescriptor.h, opensubdiv/far/patchParam.h, opensubdiv/far/patchTable.cpp, opensubdiv/far/patchTable.h, opensubdiv/far/patchTableFactory.cpp, opensubdiv/osd/CMakeLists.txt, opensubdiv/osd/cpuEvaluator.cpp, opensubdiv/osd/glslPatchShaderSource.cpp, opensubdiv/osd/glslPatchShaderSource.h, opensubdiv/osd/hlslPatchShaderSource.cpp, opensubdiv/osd/hlslPatchShaderSource.h, opensubdiv/osd/ompEvaluator.cpp, opensubdiv/osd/patchBasisCommon.h, opensubdiv/osd/tbbKernel.cpp
This is used to compute patch basis weights for
the Osd::*Evaluator classes that are unable to
use the C++ implementation from far/patchBasis.h,
e.g. the GLSL, HLSL, OpenCL, and CUDA kernels.
Instead of duplicating this code for each different
kernel language, we share a single implementation
which is minimally adapted to accommodate specific
language restrictions and syntax.
This implementation can also be used by client
shader code executed while drawing, e.g. to
compute patch basis weights for evaluating varying
and face-varying patches.
=> Added a common patchBasis implementation for Osd

opensubdiv/far/gregoryBasis.cpp, opensubdiv/far/patchTableFactory.cpp, opensubdiv/far/patchTableFactory.h
This change adds the new "useInfSharpPatch" option to Far::PatchTableFactory::Options that was previously being enabled internally.  It also includes tagging of a few additional cases as sharp and changes to the Gregory patch conversion to reflect the sharpness.
=> Exposed public patch table option to enable use of inf-sharp patches

opensubdiv/far/patchTableFactory.cpp
This change fixes regressions for legacy Gregory boundary patches that I introduced in the PatchTableFactory a while ago.
=> Fixed regressions introduced in legacy Gregory boundary patches

opensubdiv/far/patchParam.h
Given requests for the inverse of PatchParam::Normalize(), a new Unnormalize() method has been added in place of the two new mapping methods that were recently added.
=> Added inverse of Far::PatchParam::Normalize()

CMakeLists.txt, opensubdiv/CMakeLists.txt, opensubdiv/osd/CMakeLists.txt
Recent CUDA SDKs no longer support the "compute_11"
gpu architecture. We now fallback to "compute_20"
instead for newer SDK versions. Additionally, this
behavior can be overriden using the new CMake list
variable OSD_CUDA_NVCC_FLAGS so that it is easier
for clients to target newer architectures and specify
additional arguments.
Fixes #751
=> Fixed CUDA build with newer SDKs

opensubdiv/far/topologyRefiner.cpp, opensubdiv/vtr/level.cpp, opensubdiv/vtr/level.h
Adaptive refinement of face-varying data has been a bit too aggressive -- not isolating faces that are regular in face-varying space, even though an adjoining face in a completely disjoint face-varying region may have irregular features.  In order to ensure faces/patches differ by at most one level of refinement, adaptive refinement now considers all face-varying features around the corner vertices of a face, regardless of how disjoint they are.
=> Fixed overly aggressive adaptive refinement of face-varying channels

opensubdiv/far/patchTable.cpp
This fixes evaluation of face-varying patches when
the patch table has been created using Gregory basis
end caps.
=> Fixed FVar patch evaluation with Gregory basis

opensubdiv/far/stencilTableFactory.cpp
Far::LimitStencilTableFactory computes limit stencils using
patches from a Far::PatchTable, creating one temporarily if
necessary. This change propagates the useInfSharpPatch option
from adaptively refined topologies.
=> Updated LimitStencilTableFactory for InfSharpPatch

CMakeLists.txt, opensubdiv/far/patchBasis.cpp, opensubdiv/osd/glslPatchShaderSource.cpp, opensubdiv/osd/hlslPatchShaderSource.cpp, opensubdiv/osd/patchBasisCommon.h
The symbol OPENSUBDIV_GREGORY_EVAL_TRUE_DERIVATIVES
determines the method used to compute derivative weights
for Gregory basis patches.
Setting this symbol during CMake configuration (and
hence during C++ and shader compilation) will enable
the use of true derivative weights.
The default behavior is to use a simpler approximation
for consistency with earlier releases.
=> Exposed control for Gregory derivative weight eval

examples/glFVarViewer/glFVarViewer.cpp, opensubdiv/far/patchTable.cpp, opensubdiv/far/patchTable.h, opensubdiv/far/patchTableFactory.cpp, opensubdiv/osd/cpuPatchTable.cpp
The methods which return arrays of FVarPatchParam have
been made plural, e.g. GetFVarPatchParams(), for consistency
with the other methods in PatchTable.
Also fixed a missing doxygen tag.
=> Fixed naming inconsistencies in Far::PatchTable

README.md
…now that example plugin has been retired.
=> [README] Remove reference to Maya SDK 

opensubdiv/far/patchTableFactory.cpp, opensubdiv/far/primvarRefiner.h, opensubdiv/far/topologyLevel.h, opensubdiv/far/topologyRefiner.cpp, opensubdiv/vtr/fvarLevel.cpp, opensubdiv/vtr/fvarRefinement.cpp, opensubdiv/vtr/level.cpp
This set of changes includes a number of bug fixes and minor improvements to the feature tagging, adaptive refinement and construction of face-varying and inf-sharp patches.
Historically patches at smooth corners have been represented with sharp regular patches at the deepest level of refinement -- unnoticeable at a deep levels, but a poor approximation at shallow levels (and is under review for change in a later release).  While this approximation persists, for the sake of consistency, it is now being considered and applied in the context of face-varying and inf-sharp patches.
Several bugs occurring in uncommon cases were identified and fixed in the assignment and interpretation of the inf-sharp tags in face-varying channels.  A long existing bug in face-varying interpolation with the …
=> Bug fixes and improvements for face-varying and inf-sharp patches:

opensubdiv/far/patchTableFactory.cpp
Historically smooth corners have been represented with sharp patches -- isolated regular patches would use a sharp regular patch and un-isolated Gregory patches would create a sharp corner even when making it smooth was trivial.  The latter was changed recently so that corners of Gregory patches were appropriately smooth for interior inf-sharp patches.  While the smooth corners now on boundaries are a much better approximation to the limit surface, the old behavior is being restored for consistency.
=> Restore sharp approximation to smooth corners of irregular patches

opensubdiv/far/patchTableFactory.cpp
Fixed a bug in Far::PatchTableFactory to always inspect and potentially sharpen corners of irregular patches.
=> Fixed bug failing to sharpen corners of under-isolated irregular patches

opensubdiv/far/stencilTable.h
Renamed the StencilTable method Update2ndPartials()
to Update2ndDerivs() for consistency with existing API.
=> Addressed 2nd Derivative API review notes

examples/glFVarViewer/shader.glsl, opensubdiv/osd/glslPatchCommon.glsl, opensubdiv/osd/hlslPatchCommon.hlsl
This fixes the glFVarViewer to access the IsRegular bit
from PatchParam using an API wrapper rather than
directly extracting the bit. This is more consistent
with other shader API for PatchParam.
=> Addressed notes from shader API review

opensubdiv/far/patchParam.h
Fixed an incorrect type cast in Far::PatchParam
which could result in truncated FaceId values.
=> Fixed recent regression in Far::PatchParam

examples/glImaging/glImaging.cpp, examples/glImaging/shader.glsl
Fixed some incorrect shader configurations hit
while running the glImaging example through CTest
=> Fixed glImaging errors w/ ctest

cmake/FindGLFW.cmake
There is more we can clean up here, but this
fixes link issues while building on X11 platforms
when using cmake 3.x
=> Fixed cmake GLFW X11 link dependencies

README.md
This patch removes some extra `-D` flags that are located in the CMake build snippets. The extra `-D`'s prevent copy and pasting to run the build examples. There was also a trailing white space, so that was also removed.
=> Resolve readme CMake snippet typos

examples/glEvalLimit/glEvalLimit.cpp, examples/glEvalLimit/init_shapes.h, examples/glFVarViewer/glFVarViewer.cpp, opensubdiv/far/stencilTableFactory.cpp, opensubdiv/far/stencilTableFactory.h
Extended Far::StencilTableFactory to support the creation
of stencil tables for face-varying channels. We already
use stencil tables to compute local point face-varying values.
These changes allow a stencil table to be created which
refines face-varying primvar data for all refined points.
=> Support creation of Face-varying stencil tables

CMakeLists.txt
Previously, glew was forced to static linkage on windows, even when
dynamic Glew libraries were linked which would result in linker errors.
In this change, static glew libraries are detected by looking for the "s"
suffix convention on the library (though, maybe this should be handled in
the FindGlew module).
Change cherry-picked by davidgyu from jcowles branch
=> WIN32 Glew fixes to CMakeLists.txt

CMakeLists.txt
This is a simplified implementation of the work by thomthom to add
support for linking the osd libraries with the static C runtime library
on Windows. We will likely revisit this when we finish adding support
for building the osd libraries as DLLs on Windows.
=> Added option to build using MSVC with static CRT.

opensubdiv/osd/glComputeEvaluator.cpp
This fixes an inadvertant double delete of the previous GL progam
when compiling a compute kernel.
Fixes #880
=> Fixed program delete in Osd::GLComputeEvaluator

examples/glViewer/glViewer.cpp, opensubdiv/far/patchTableFactory.cpp, opensubdiv/far/patchTableFactory.h, opensubdiv/osd/mesh.h
Historically, smooth corner features have been approximated with regular B-Spline patches without any attempt to make the corner of the patch smooth to match the true limit surface.  So a smooth boundary is effectively approximated with a sharp one.  This is one of the few cases where the corners of the patch do not match the limit surface and makes for a poor approximation at low levels of isolation.
This set of changes exposes an internal option to use irregular patches at smooth corners to better approximate the true limit surface.  The legacy behavior of using sharp patches to approximate smooth corners is preserved by default but can now be overridden.  The new option has been exposed in examples/glViewer.
As a future improvement, when choosing B-Spline patches for irregular features …
=> Expose public option to improve sharp patches at smooth corners

examples/glEvalLimit/glEvalLimit.cpp, opensubdiv/osd/clEvaluator.cpp, opensubdiv/osd/clEvaluator.h, opensubdiv/osd/clKernel.cl, opensubdiv/osd/cpuEvaluator.cpp, opensubdiv/osd/cpuEvaluator.h, opensubdiv/osd/cpuKernel.cpp, opensubdiv/osd/cpuKernel.h, opensubdiv/osd/cudaEvaluator.cpp, opensubdiv/osd/cudaEvaluator.h, opensubdiv/osd/cudaKernel.cu, opensubdiv/osd/d3d11ComputeEvaluator.cpp, opensubdiv/osd/d3d11ComputeEvaluator.h, opensubdiv/osd/glComputeEvaluator.cpp, opensubdiv/osd/glComputeEvaluator.h, opensubdiv/osd/glXFBEvaluator.cpp, opensubdiv/osd/glXFBEvaluator.h, opensubdiv/osd/glslComputeKernel.glsl, opensubdiv/osd/glslXFBKernel.glsl, opensubdiv/osd/mesh.h, opensubdiv/osd/ompEvaluator.cpp, opensubdiv/osd/ompEvaluator.h, opensubdiv/osd/ompKernel.cpp, opensubdiv/osd/ompKernel.h, opensubdiv/osd/tbbEvaluator.cpp, opensubdiv/osd/tbbEvaluator.h, opensubdiv/osd/tbbKernel.cpp, opensubdiv/osd/tbbKernel.h
This pull request is broken out into several parts:
The main change is to implement the Osd Evaluator methods
EvalStencils(), EvalPatches, EvalPatchesVarying, and
EvalPatchesFaceVarying to compute 1st and 2nd derivatives.
This also fixes several inconsistencies in the doxygen comments
for these classes.
And also includes the addition of the display of Mean Curvature
in the glEvalLimit viewer to help exercise the 2nd derivative
computations.
=> Updated Osd Evaluator methods for derivative eval

examples/glEvalLimit/glEvalLimit.cpp, opensubdiv/osd/glXFBEvaluator.cpp, opensubdiv/osd/glXFBEvaluator.h, opensubdiv/osd/glslXFBKernel.glsl
Most GL implementations support a maximum of 4 transform
feedback buffer bindings. With the addition of 1st and 2nd
derivative evaluation up to 6 bindings might be required,
i.e. dst, du, dv, duu, duv, dvv.
This change extends the GLXFB Evaluator interface to allow
a client to specialize the evaluator when it is known that
(at least) the 1st derivative and 2nd derivative outputs
are interleaved together into shared buffers.
When this option is used, the maximum number of transform
feedback buffer bindings can be reduced to 3 instead of 6.
=> Improved XFB Evaluation of 1st and 2nd derivatives

opensubdiv/far/endCapBSplineBasisPatchFactory.cpp, opensubdiv/far/endCapGregoryBasisPatchFactory.cpp, opensubdiv/far/patchTableFactory.cpp, opensubdiv/far/stencilTableFactory.cpp
The warning flags for GCC do not enable shadowing warnings, which will appear for ICC.  Such warnings were eliminated in the 3.0 source but a few have crept into new code written since.  All of the occurrences are in opensubdiv/far and are corrected here.
I'd prefer we enable -Wshadow for GCC at some point -- even if only for the core library source -- as some of the cases not detected can be pitfalls for someone modifying existing code.
There are a manageable number of cases to deal with in the examples.  Unfortunately, the template-heavy code included from opensubdiv/hbr is riddled with such warnings -- we could eliminate these but since Hbr is being phased out, removing Hbr dependent code from the examples would be preferable.  There are also external header files included that will …
=> Removed shadowing warnings from source for core libraries

.gitignore, README.md, build_scripts/travis_before_script_linux.sh, build_scripts/travis_script_linux.sh, build_scripts/travis_script_osx.sh, examples/common/glUtils.cpp, regression/osd_regression/main.cpp
- Added support for OSX CI builds and tests
- Cleaned up build scripts and moved to $ROOT/build_scripts
- On Linux: moved to trusty distro
- On Linux: enabled OpenMP, TBB and PTex build options
- On Linux: install and setup xvfb with newer mesa drivers to run our GL tests
- On Linux: enable GL tests
=> Several improvements to CI building and testing

examples/mtlViewer/mtlViewer.mm
Updated the mtlViewer to compute correct offsets
for face-varying param and index buffers when using
the Gregory Basis end cap approximation.
=> Fixed mtlViewer face-varying evaluation

examples/mtlPtexViewer/mtlPtexViewer.mm
Updated mtlPtexViewer to account for recent
API changes to Osd::MTLPatchShaderSource and
also fixed a build error when building with
the use of PtexCache disabled.
=> Fixed mtlPtexViewer build

opensubdiv/osd/mtlComputeEvaluator.h, opensubdiv/osd/mtlComputeEvaluator.mm, opensubdiv/osd/mtlComputeKernel.metal
Updated MtlComputeEvaluator documentation to be
consistent with the documentation for other compute
evaluator implementations and fixed missing or
incorrect doxygen tags.
Also, updated the overloads for the EvalStencils
and EvalPatches methods to account for 1st and
2nd derivative evaluation.
=> Fixed MtlComputeEvaluator docs and overloads

opensubdiv/osd/mtlPatchShaderSource.mm
This fixes a shader compile error when enabling
the OPENSUBDIV_GREGORY_EVAL_TRUE_DERIVATIVES option.
=> Fixed a typo in MTLPatchShaderSource

opensubdiv/far/patchTableFactory.cpp, opensubdiv/far/patchTableFactory.h
Corrected some minor issues related to indices of face-varying patches in uniform patch tables that may have caused problems in rare circumstances.  
In response to issue #737, also made the indexing discrepancy between vertex/varying patches and face-varying patches clearer with internal options and new Doxygen comments.
=> More fixes for face-varying patches in uniform PatchTables

opensubdiv/osd/glslPatchCommon.glsl
As noted in Issue #947, GPU shaders do not bother to compute proper unit normal vectors in some common cases where the cross product of dPdu and dPdv is zero.  This change updates the GLSL patch evaluation shaders to do so.  The revised evaluation should not degrade performance and no changes to the public shader API were made.  For those using the shaders to evaluate partial derivatives of the normal vector (dNdu and dNdv), a bug involving the magnitudes of these derivatives was corrected and so may lead to some change in behavior.
The BSpline patch evaluation uses conversion to a Bezier patch and then invokes the Bezier patch evaluation, but the Gregory patch evaluation was unfortunately duplicating the code for Bezier patch evaluation inline.  So the Gregory patch evaluation was first …
=> Improved GLSL patch shaders to compute normals in common degenerate cases

opensubdiv/far/endCapBSplineBasisPatchFactory.cpp, opensubdiv/far/endCapGregoryBasisPatchFactory.cpp, opensubdiv/far/endCapLegacyGregoryPatchFactory.cpp
Fixed a couple of bugs reserving memory during creation of Far::PatchTables for large data sets.  Estimated upper bounds use the product of two sizes declared as "int"  which overflows and results in negative values passed to vector::reserve() (and so cast to "size_t" and crashing) instead of the smaller fixed positive size that was intended in such cases.
=> Fixed integer overflow bugs for large meshes in PatchTable factories

examples/mtlViewer/init_shapes.h, opensubdiv/osd/mtlPatchCommon.metal
Updated Metal patch shaders to resolve degenerate normals
to address #947. This fix was ported from the GLSL patch
shader source.
Also, added missing inf sharp test cases to mtlViewer.
=> Metal patch shader changes for degenerate normals

examples/dxViewer/init_shapes.h, opensubdiv/osd/hlslPatchCommon.hlsl
Updated HLSL patch shaders to resolve degenerate normals
to address #947. This fix was ported from the GLSL patch
shader source.
Also, added missing inf sharp test cases to dxViewer.
=> HLSL patch shader changes for degenerate normals

opensubdiv/far/patchTableFactory.cpp
Recent refactoring of PatchTable construction (#966) introduced a regression with the construction of patches for Varying data.  The bilinear patches would be generated in an incorrect order when more than one array of patches was being constructed, i.e. Gregory patches were used for the irregular patches.  When both regular and irregular patches were represented with BSplines, use of a single patch array avoided the problem.
=> Fixed regression in PatchTable construction with varying patches

opensubdiv/far/topologyRefiner.cpp
The issue is that FeatureMask structure has size of an integer, but only
first 11 bytes are initialized, the rest is left non-initialized to a
stack memory of RefineAdaptive(). This will cause issues with IsEmpty()
which check whether any of integer's bits are set, effectively causing
jumps dependent on a non-initialized memory.
=> Fix uninitialized stack memory used in topology refiner

regression/common/shape_utils.cpp
It's possible that `gets()` returns empty line, doing `strlen(line) - 1` will cause access of negative element of a line.
=> Fix buffer underflow when reading OBJ data

opensubdiv/far/bilinearPatchBuilder.cpp, opensubdiv/far/bilinearPatchBuilder.h, opensubdiv/far/catmarkPatchBuilder.cpp, opensubdiv/far/catmarkPatchBuilder.h, opensubdiv/far/loopPatchBuilder.cpp, opensubdiv/far/loopPatchBuilder.h, opensubdiv/far/patchBasis.cpp, opensubdiv/far/patchBasis.h, opensubdiv/far/patchBuilder.cpp, opensubdiv/far/patchBuilder.h, opensubdiv/far/patchTableFactory.cpp, opensubdiv/sdc/catmarkScheme.h, opensubdiv/sdc/loopScheme.h
This set of changes improves some of the low-level numerical calculations in Sdc and Far to expand the use of templates in support of double precision.  No public interfaces are affected at this time.
The Sdc schemes were updated to correct some oversights in their support of precision templates (retention of full precision with literal constants, use of std math functions, etc).  Similar computations in Far::CatmarkPatchBuilder were reformatted to support templates for precision.  The Far::PatchBuilder and its usage was extended to make greater use of the SparseMatrix template, and all patch basis evaluation was converted to templates.
=> Internal improvements to support double precision

opensubdiv/far/catmarkPatchBuilder.cpp
This is a trivial superficial change that was meant to be included in a recent pull request (#977) -- just reordering the header files in a single source file to conform to established convention.
=> Superficial header reordering in far/catmarkPatchBuilder.cpp

opensubdiv/far/primvarRefiner.h
Fixed the method signature of the internal limitFVar method to make
the dst argument a reference rather than a pointer to be more consistent
with earlier changes for other primvar classes. This also makes it
easier to use the public template LimitFaceVarying method to operate
on a wider range of primvar container types.
=> Fixed Far::PrimvarRefiner::limitFVar prototype

opensubdiv/far/patchBasis.cpp, opensubdiv/far/patchMap.h, opensubdiv/far/patchParam.h, opensubdiv/far/patchTable.cpp, opensubdiv/far/patchTable.h, opensubdiv/far/patchTableFactory.cpp, opensubdiv/far/patchTableFactory.h, opensubdiv/far/primvarRefiner.h, opensubdiv/far/stencilBuilder.cpp, opensubdiv/far/stencilBuilder.h, opensubdiv/far/stencilTable.cpp, opensubdiv/far/stencilTable.h, opensubdiv/far/stencilTableFactory.cpp, opensubdiv/far/stencilTableFactory.h, opensubdiv/far/topologyRefiner.h, regression/far_perf/far_perf.cpp, tutorials/far/tutorial_6/far_tutorial_6.cpp
This set of changes extends the public interface of classes within Far to support double precision.  It achieves the goals of #900 while impacting fewer public classes and preserving the existing public interface.  The changes are applied in two groups/commits.
The first impacts classes that are topological in nature and whose interface only marginally involves floating point values, e.g. Far::PatchTable, Far::PatchParam, etc.  Public methods of these classes that involve floating point values are extended to template methods.  Additional overloads are provided for compatibility in cases where existing usage creates template parameter resolution issues.
The second impacts classes whose primary function is to manage or compute floating point values, e.g. the Stencil classes (along with …
=> Extend the public interface of Far to support double precision

opensubdiv/far/catmarkPatchBuilder.cpp, opensubdiv/far/stencilTableFactory.h
These changes correct a couple of oversights in the many changes that have been pulled recently in support of double precision in Far:
- fixed the LimitStencilTableFactory wrapper class to accept a StencilTable in its create method instead of a LimitStencilTable
- promoted declaration of a set of constants in CatmarkPatchBuilder to retain double precision
=> Fix minor oversights in recent changes supporting double precision

opensubdiv/far/stencilTableFactory.cpp
This change extends Far::StencilTableFactory::AppendLocalPointStencilTable() to support the case when the base StencilTable is empty or un-specified (passing an empty base StencilTable will currently crash).  This case can occur when no adaptive refinement is applied but local points are present for any patch conversions.
=> fix Far::StencilTable append when base StencilTable empty

opensubdiv/osd/mesh.h
There has long been a bilinear end-cap option in Far::PatchTableFactory::Options but it has been missing from Osd::MeshBits.  This change adds it so the two sets of choices are consistent and we can start making use of the linear option in the example applications and elsewhere.  (Note that there is a bug with face-varying linear end-caps that is still being resolved.)
=> Added bilinear end-cap option to Osd::MeshBits

build_scripts/travis_before_script_linux.sh
Try to improve the stability of the travis-ci linux
build by running apt-get update before installing X11
dev dependencies.
=> Fixed travis-ci build scripts

opensubdiv/far/patchTable.h, opensubdiv/far/patchTableFactory.cpp, opensubdiv/far/patchTableFactory.h, opensubdiv/far/stencilTable.h, opensubdiv/far/topologyRefiner.cpp, opensubdiv/far/topologyRefiner.h, opensubdiv/far/topologyRefinerFactory.h, tutorials/far/CMakeLists.txt, tutorials/far/tutorial_9/CMakeLists.txt, tutorials/far/tutorial_9/far_tutorial_9.cpp
This set of changes includes several minor extensions to Far classes (typically overloading a method) to help deal with PatchTables for really large meshes.  The time and space required to build a single large PatchTable for evaluation or tessellation can be objectionable, and that construction cannot be threaded.  Each of the changes here is relatively minor, but by dealing with arbitrary pieces of the mesh and a common base level more easily, their combined use provides a lot of flexibility in dealing with large meshes
The changes include:
- overloading PatchTable construction to restrict the patches constructed to a subset of base faces
- overloading adaptive refinement to restrict refinement to a subset of base faces
- overloading TopologyRefiner construction allowing a new instance …
=> Minor extensions to Far classes to help manage large PatchTables

opensubdiv/far/stencilTable.h
As raised in Issue #992, this change fixes the omission of the "public" keyword when deriving Far::LimitStencil from the new template class Far::LimitStencilReal<float>.
=> Fixed oversight deriving Far::LimitStencil from new template class

opensubdiv/far/patchTable.h, tutorials/far/tutorial_6/far_tutorial_6.cpp, tutorials/far/tutorial_9/far_tutorial_9.cpp
As part of the changes providing double precision support (#980), the behavior of Far::PatchTable::ComputeLocalPointValues() et al was extended to apply the local point stencil tables to client primvar data conditionally, according to whether stored in the PatchTable as single or double precision.  This ends up requiring both single and double versions of generic stencil application to be instantiated, and the implementation of a client's primvar type T may not be written to support both -- often T::AddWithWeight() will produce warnings or errors when given a double precision stencil weight and expecting float.
Since ComputeLocalPointValues() et al are simple one-line wrappers around the stencil tables' UpdateValues() method, we are reverting their implementations to operate only in the …
=> Reverted PatchTable local point methods to address template issues

opensubdiv/far/patchTable.cpp, opensubdiv/far/patchTable.h, opensubdiv/far/patchTableFactory.cpp, opensubdiv/osd/cpuEvaluator.cpp, opensubdiv/osd/cpuPatchTable.cpp, opensubdiv/osd/types.h
This change extends the public interface of the Far::PatchTable and related Osd classes to allow proper handling of face-varying patch arrays -- which store patches of two different types in the same array.
Two changes are made in both areas:
- a second patch descriptor is now explicitly associated with the array and methods are provided to query both a "regular" and "irregular" patch type (typically in response to the result of the PatchParam::IsRegular() test).  Previously the irregular patch type was available in the descriptor and the regular type was assumed to be BSpline, which will not be the case if the subdivision scheme is not Catmark.
- a common stride for patches in the array is determined as the max of the regular and irregular patch sizes and provided with a new access …
=> Extended face-varying patch arrays to properly support two types

opensubdiv/far/topologyRefiner.cpp
This change removes the restriction limiting adaptive refinement to the Catmark scheme -- a prerequisite to building patches for Bilinear and Loop.
Adaptive refinement has generally worked for triangles since 3.0, but a couple of subtle issues remained. The change here mainly deals with forced isolation of boundary features that has been present for quads since 2.x. For triangles, a single level of refinement does not isolate boundary features -- refinement of a regular corner triangle with three boundary vertices produces a new child face at the corner that also has three boundary vertices. We don't want such regular faces refined to the maximum depth, and there is no gain in refining at least once, so the adaptive analysis does not force boundary isolation on regular triangles as it …
=> Remove Catmark-only restriction on adpative refinement in Far

opensubdiv/vtr/level.cpp, opensubdiv/vtr/level.h
Low-level bitfields that were designed to support bitwise operations make use of pointer casting in those operations, which causes problems when setting high levels of optimization in older versions of GCC.  Replacing the type casting with more explicit retrieval and assignment of the bits as integers avoids the issue and also simplifies the implementation.
=> Simplify Vtr bitfield operations to avoid issues with older versions of GCC

opensubdiv/far/patchBasis.cpp, opensubdiv/far/patchBasis.h, opensubdiv/far/patchDescriptor.cpp, opensubdiv/far/patchDescriptor.h, opensubdiv/far/patchMap.cpp, opensubdiv/far/patchMap.h, opensubdiv/far/patchParam.h, opensubdiv/far/patchTable.cpp, opensubdiv/far/patchTableFactory.cpp, opensubdiv/osd/clKernel.cl, opensubdiv/osd/cudaKernel.cu, opensubdiv/osd/glslComputeKernel.glsl, opensubdiv/osd/glslPatchCommon.glsl, opensubdiv/osd/glslXFBKernel.glsl, opensubdiv/osd/hlslPatchCommon.hlsl, opensubdiv/osd/mtlComputeKernel.metal, opensubdiv/osd/mtlPatchCommon.metal
This set of changes lays the groundwork for upcoming PatchTables of triangular patches for Loop subdivision.  Minor extensions to some of the low level patch utility classes such as PatchDescriptor and PatchParam are made, basis evaluation is added for the new triangular patch types, and other related utilities such as PatchMap are updated.  All existing functionality for quad patches should remain unaffected.
One minor change with more significant impact is the extension of the boundary mask in PatchParam from four to five bits to support the needs of triangular patches (which can have boundary vertices without boundary edges).  Extending that mask by one bit shifts the four bits that are currently used, so all Osd evaluators that access the boundary field without the use of the …
=> Added low-level support in Far for triangular patches

opensubdiv/far/loopPatchBuilder.cpp, opensubdiv/far/patchBuilder.cpp, opensubdiv/far/patchBuilder.h
This set of changes populates the Far::PatchTable with triangular patches representing the limit surface of a Loop subdivision mesh.
PatchTable construction was previously factored to assemble the tables in more general terms, so no changes to the factory were necessary here.  The internal PatchBuilder base class and its LoopPatchBuilder subclass are extended here to support triangular patches.  The base class handles the topological inspection and extraction of regular patches while the subclass handles the conversion of irregular patches to the supported triangular patch types:  linear, Gregory and the regular Box-spline.
This completes support for Loop limit patches in Far, so tessellation of the limit surface for Loop is now possible via the PatchTable.  The various Osd evaluators and …
=> Populate Far::PatchTable with triangular patches for Loop scheme

examples/common/objAnim.cpp, examples/common/objAnim.h, regression/common/far_utils.h, tutorials/far/tutorial_9/far_tutorial_9.cpp
These changes included a couple of additions making it easier for examples and tutorials to specify the subdivision scheme for a given .obj file (since the extended syntax does not include the scheme type).  The far/tutorial_9 was updated to make use of the new functionality.
=> Added more common utilities for Shapes from .obj files:

opensubdiv/far/topologyRefinerFactory.h
Renamed a method argument to suppress Doxygen warnings for Far::TopologyRefinerFactory::Create().
=> Fixed Doxygen warning in far/topologyRefinerFactory.h

opensubdiv/far/patchTableFactory.cpp
The varying descriptor of Far::PatchTable is used elsewhere to determine if the table contains triangular or quad patches, but that descriptor is not being initialized if generating varying patches is suppressed, e.g. in far/tutorial_9.  This change initializes the descriptor on construction regardless of whether varying patches are generated.  (Meanwhile alternatives to the use of the varying descriptor are under consideration.)
=> Fix initialization of PatchTable's varying patch descriptor

opensubdiv/far/stencilTable.h
This change address inconsistencies in the Far interfaces used to interpolate primvar data.  The Far::StencilTable method UpdateValues() takes raw pointer arguments of a single template type <T> while the Far::PrimvarRefiner takes references to different types <T> and <U> for source and destination values.  The latter use of references is more flexible -- allowing both raw pointers as well as other container types supporting [] -- so the limitations of the former prevent local patch points or other Far::StencilTables from being interpolated with types that the PrimvarRefiner supports.
Far::StencilTable::UpdateValues() is updated here to use the same pattern as Far::PrimvarRefiner with its reference arguments and multiple template parameters <T> and <U>.  The existing pointer interfaces …
=> Extend Far::StencilTable data interpolation interfaces

opensubdiv/far/patchBuilder.cpp, opensubdiv/far/topologyRefinerFactory.cpp, opensubdiv/vtr/level.h
Patches around non-manifold vertices have historically been approximated with regular patches, which leaves gaps when an irregular patch is warranted (the catmark_fan shape has illustrated this in the viewer examples).  This change constructs irregular patches where necessary to eliminate gaps.  The faces around a non-manifold vertex are now partitioned into groups delimited by boundary, non-manifold or inf-sharp edges, with each group containing a continuous set of patches.
=> Improve patch construction around non-manifold vertices to close gaps

opensubdiv/far/patchBuilder.cpp, opensubdiv/far/patchBuilder.h
These changes improve the Far::PatchBuilder's inspection and classification of patch properties to better deal with features that are not isolated.  Previous assumptions that features were isolated via adaptive refinement are not met in the case of Catmark subdivision at level 1 when non-quad faces are present in the base level, and logic to deal with this case was scattered in several places.
The initial test to determine if a patch is regular was re-organized (and better documented) to emphasize whether irregular features are isolated and to deal with one or all accordingly.  Greater use of bit masks is also applied here and elsewhere to simplify dealing with the public options that need to be supported while more efficient acceptance/rejection tests were also added to handle common …
=> Improved Far::PatchBuilder's determination of patch properties

opensubdiv/far/patchBasis.cpp, opensubdiv/far/patchBasis.h, opensubdiv/far/patchTable.cpp, opensubdiv/osd/cpuEvaluator.cpp, opensubdiv/osd/ompEvaluator.cpp, opensubdiv/osd/tbbKernel.cpp
These changes simplify the internal patch basis evaluation functions in far/patchBasis.h.  The functions for each basis now deal purely in a normalized (s,t) space and are completely independent of Far::PatchParam.  A single pair of higher-level evaluation functions now deals with dependencies on Far::PatchParam (e.g. derivative magnitude scaling) and dispatches the basis evaluation for a given patch type.
Usage of the individual basis methods in Far::PatchTable and the Osd evaluators was replaced with one of the new functions taking a patch type and PatchParam.  Upcoming work in Osd will further align osd/patchBasisCommon and the Osd evaluators with these changes.
=> Minor refactoring of Far patch basis evaluation methods

opensubdiv/far/patchBuilder.cpp, opensubdiv/far/patchBuilder.h, opensubdiv/far/topologyRefiner.cpp, opensubdiv/far/topologyRefiner.h, opensubdiv/far/topologyRefinerFactory.cpp, opensubdiv/far/topologyRefinerFactory.h, opensubdiv/vtr/level.h, opensubdiv/vtr/refinement.cpp
These changes add new vertex tags and members to improve the detection of irregular faces during adaptive refinement and patch construction.  With the recent addition of adaptive refinement and patches for a selected set of faces, the need to determine if a face is, or is incident to, an irregular face has become more necessary -- and detecting if a neighboring face is irregular requires a tedious topological search around the entire neighborhood of the face (inspection of all faces around all corner vertices).
A new vertex tag was added to indicate a vertex is incident one or more irregular faces while a new member was added to the TopologyRefiner to detect the presence of irregular faces in the base level (similar to that for face holes).  The new tag is explicitly assigned only when …
=> Extended Far topology tagging to better handle irregular faces

opensubdiv/far/patchTable.cpp, opensubdiv/far/patchTable.h, opensubdiv/far/patchTableFactory.cpp
The little-used but public IsFeatureAdaptive() query of Far::PatchTable is hard-coded to use patch types used by the Catmark scheme to determine its result, so it does not work for PatchTables populated by the Loop or Bilinear schemes.
Since the result cannot be determined solely by inspecting the patch types (adaptive patches for Bilinear will all be quads) a new member was added to PatchTable and initialized on construction by the PatchTableFactory.  The member exists solely to support IsFeatureAdaptive() at this point -- which is used within the LimitStencilTableFactory -- and no additional public access to it is provided at this time.
=> Fixed Far::PatchTable::IsFeatureAdaptive() to work for all schemes

opensubdiv/far/topologyRefiner.cpp
This change fixes a regression introduced by #1016 in adaptive refinement.  An irregular face > 4 needs to be rejected before the tags are gathered and combined, otherwise the array on the stack overflows.
=> Fixed adaptive refinement regression with recent irregular face changes

opensubdiv/far/patchMap.cpp, opensubdiv/far/patchMap.h
These changes address two limitations in the Far::PatchMap.
For the first, the use of PatchParam bits in constructing the quadtree for rotated triangular patches turned out not to work for all cases of adaptive refinement (e.g. when features were present along edges rather than vertices), so it was replaced with a construction strategy that more closely matches the search.  This lead to some refactoring of the PatchMap initialization to support the differing and common needs of quad and triangular construction.
The second limitation was the treatment of the indices of faces from which the patches in the given PatchTable originated.  Since the PatchTable does not retain the topology of the mesh from which patches were constructed, the PatchMap tried to infer the set of originating faces by …
=> Improve Far::PatchMap for sparse and triangular patch tables

examples/glFVarViewer/glFVarViewer.cpp, examples/glFVarViewer/shader.glsl, opensubdiv/osd/CMakeLists.txt, opensubdiv/osd/clEvaluator.cpp, opensubdiv/osd/clKernel.cl, opensubdiv/osd/cpuEvaluator.cpp, opensubdiv/osd/cudaKernel.cu, opensubdiv/osd/glComputeEvaluator.cpp, opensubdiv/osd/glComputeEvaluator.h, opensubdiv/osd/glXFBEvaluator.cpp, opensubdiv/osd/glXFBEvaluator.h, opensubdiv/osd/glslComputeKernel.glsl, opensubdiv/osd/glslPatchShaderSource.cpp, opensubdiv/osd/glslXFBKernel.glsl, opensubdiv/osd/hlslPatchShaderSource.cpp, opensubdiv/osd/mtlComputeKernel.metal, opensubdiv/osd/mtlPatchShaderSource.mm, opensubdiv/osd/ompEvaluator.cpp, opensubdiv/osd/patchBasisCommon.h, opensubdiv/osd/patchBasisCommonEval.h, opensubdiv/osd/patchBasisCommonTypes.h, opensubdiv/osd/tbbKernel.cpp
This updates the patch basis evaluation functions in Osd
to match recent changes to far/patchBasis.
This also exposes a common facility for dealing with PatchCoord,
PatchArray, and PatchParam. These are exposed as global functions
operating on struct data, since C++ style class methods are not
supported by all of the Osd shader and kernel execution envirionments.
Changes:
- Merged far/patchBasis.cpp to osd/patchBasisCommon{,Types,Eval}.h
- Exposed PatchCoord, PatchArray, and PatchParam to Osd kernels
- exposed OsdEvaluatePatchBasis and OsdEvaluatePatchBasisNormalized
- Updated CPU, TBB, Omp, CUDA, OpenCL, GLSL, HLSL, and Metal evaluators
- Updated glFVarViewer
=> Improved patch basis eval for Osd to match Far

opensubdiv/far/catmarkPatchBuilder.cpp, opensubdiv/far/loopPatchBuilder.cpp, opensubdiv/far/patchBuilder.h
These changes fix some rare bugs in the internal PatchBuilder subclasses that can occur when constructing patches from faces whose boundary features have not been isolated.
When boundary features are isolated (currently the norm), two adjacent corners of a patch that are tagged as boundaries are guaranteed to be on the same boundary edge.  This is not the case when not isolated, and more clearly tagging the boundary edges avoids misinterpeting the boundary features present.
=> Minor fixes to PatchBuilders related to boundary isolation assumptions

opensubdiv/far/patchDescriptor.cpp, opensubdiv/far/patchDescriptor.h
This change updates a few obscure Far::PatchDescriptor methods to account for current support of patches for all subdivision schemes.  The reference to "adaptive" patch types makes less sense these days (linear patches can be used in an adaptive context, non-linear patches potentially in a uniform context) so we interpret an adaptive patch type as historically non-linear.
=> Updated Far::PatchDescriptor methods involving "adaptive" patch types

opensubdiv/far/patchMap.h
This change corrects a bug in the construction of a Far::PatchMap for triangular patches that occurs when building a PatchMap for a uniform PatchTable at level 3 or greater.
=> Fixed bug in Far::PatchMap for rotated triangular patches

opensubdiv/far/patchBuilder.cpp, opensubdiv/far/patchBuilder.h, opensubdiv/far/patchTableFactory.cpp
With patch evaluation in both Far and Osd relying more on the "IsRegular" bit of Far::PatchParam, the bits of the PatchParams for the regular and irregular arrays in a PatchTable have been updated to reflect that regular/irregular status.  The PatchBuilder method most often used to initialize the PatchParam of each patch was extended to optionally specify the value of the regular bit and its usage updated to do so.
=> Assign Far::PatchParam's regular bit consistent with Osd::PatchArray

opensubdiv/far/patchBuilder.cpp
This change fixes a regression for triangular patches that cropped up when simplifying the topological analysis of patches.  When determining the boundary mask of a triangular patch whose apex lies on an interior infinitely sharp edge, the bit indicating the vertex has incident inf-sharp edges should be used rather than the bit indicating the vertex itself is inf-sharp.
=> Fixed triangular patches at interior infinitely sharp edges

opensubdiv/far/patchBuilder.cpp, regression/shapes/all.h, regression/shapes/bilinear_nonplanar.h, regression/shapes/bilinear_nonquads0.h, regression/shapes/bilinear_nonquads1.h
This change completes adaptive generation of patches for the Bilinear scheme and includes new regression/shapes.
For non-quad faces the patch generation needed adjustment to exclude incomplete faces that are generated at level 1 from the adaptive refinement -- that made it easier to consider Bilinear with other schemes and simplify patch inspection in terms of base and refined faces.
The new regression shapes include two exhibiting non-quads and one with highly non-planar quads.  These will be included in some of the example programs in conjunction with other work on those examples.
=> Patch construction and more regression shapes for Bilinear scheme

opensubdiv/vtr/fvarLevel.h
With the recent removal of the restriction that patches around non-manifold vertices be regular, face-varying patches whose topology does not match warrants a little more care.  Regardless of the face-varying topology, the fact that the vertex is non-manifold makes is necessary to perform a non-manifold search for the span containing the face of the patch.  So the initialization of the face-varying tags is updated here to ensure that the non-manifold bit of the vertex is always included to trigger the appropriate search.
=> Fix construction of face-varying patches around non-manifold vertices

opensubdiv/osd/glslPatchBoxSplineTriangle.glsl, opensubdiv/osd/glslPatchCommon.glsl, opensubdiv/osd/glslPatchCommonTess.glsl
This pull request changes the GLSL representation of the regular box-spline triangle for Loop subdivision from a hybrid Bezier triangle (cubic boundaries with quartic interior) to a fully quartic Bezier triangle.  This addresses cracks that can appear between subdivision levels as the cubic boundary curves are only a close approximation to the true quartic boundaries of the Box-spline.
The GLSL shaders for the Box-spline triangle were updated to accommodate the 15-points of the quartic Bezier triangle.  The Bezier triangle evaluation was updated for a fully quartic triangle, and code was added to resolve degenerate normals using tolerances similar to those for quadrilateral patches.  The adaptive tessellation metrics for Bezier triangles were also updated to use quartic rather than cubic …
=> Changed GLSL conversion of regular Loop patch to quartic Bezier

opensubdiv/far/loopPatchBuilder.cpp, opensubdiv/far/patchBasis.cpp, opensubdiv/far/patchBasis.h, opensubdiv/far/patchDescriptor.h, opensubdiv/far/patchTableFactory.cpp, opensubdiv/osd/glslPatchCommon.glsl, opensubdiv/osd/glslPatchCommonTess.glsl, opensubdiv/osd/glslPatchGregoryTriangle.glsl, opensubdiv/osd/patchBasisCommon.h, opensubdiv/osd/patchBasisCommonEval.h
These changes extend the triangular Gregory patch used to represent irregular areas of Loop subdivision from the cubic/quartic hybrid patch (cubic boundaries with quartic interior) to a full quartic.  This eliminates cracks between the Gregory and regular patches.
Construction of the Gregory triangle and basis evaluation for both the quartic Gregory triangle and its Bezier counterpart were updated in Far (and a long-standing tangent continuity bug near boundaries fixed in the process).  The Osd counterparts for basis evaluation were synchronized with the Far changes and the GLSL shaders for the Gregory triangle updated to quartic Bezier for both evaluation and adaptive tessellation.
=> Extended triangular Gregory patch to full quartic

opensubdiv/osd/glslPatchGregoryTriangle.glsl
The point indices used to interpolate varying data should
be the points at the outer corners of the patch.
=> Fixed varying interp for gregory triangle patches

opensubdiv/osd/glslPatchBSpline.glsl, opensubdiv/osd/glslPatchBoxSplineTriangle.glsl, opensubdiv/osd/glslPatchCommonTess.glsl, opensubdiv/osd/glslPatchGregoryTriangle.glsl
This change attempts to clarify and simplify the higher level GLSL functions used to determine adaptive tessellation levels for the different patch types.  When a function accepts and interprets a set of control points specific to a particular patch type, it is now expect to reflect that patch type in its name.  This succeeds the original "LimitPoints" naming of functions (kept for compatibility) which pre-dated the set of patch types that are now supported.
The code dealing with patches at transition levels was also factored to more generally deal with a set of corners and midpoints of the patch boundaries.  Functions for specific patch types now need only compute the required corners and midpoints as best suits that type.
=> Minor refactoring of GLSL functions to compute adaptive tess levels

opensubdiv/far/patchDescriptor.h
The IsAdaptive() test was previously modified to use the number of control points to detect non-linear patches requiring tessellation, but legacy Gregory patches are of size 4.  So the patch type must ultimately be inspected (with or without the patch sizes).
=> Fixed Far::PatchDescriptor::IsAdaptive() for legacy Gregory

examples/glEvalLimit/glEvalLimit.cpp, examples/glEvalLimit/init_shapes.h, examples/glFVarViewer/glFVarViewer.cpp, examples/glFVarViewer/init_shapes.h, examples/glImaging/glImaging.cpp, examples/glImaging/init_shapes.h, examples/glImaging/shader.glsl, examples/glPaintTest/glPaintTest.cpp, examples/glPaintTest/init_shapes.h, examples/glPtexViewer/glPtexViewer.cpp, examples/glPtexViewer/shader.glsl, examples/glShareTopology/glShareTopology.cpp, examples/glShareTopology/init_shapes.h, examples/glShareTopology/sceneBase.h, examples/glShareTopology/shader.glsl, examples/glStencilViewer/glStencilViewer.cpp, examples/glStencilViewer/init_shapes.h, examples/glViewer/glViewer.cpp, examples/glViewer/init_shapes.h
These changes include several minor updates to the examples under examples/gl*.
The primary purpose was to ensure all function correctly when patches are built (via adaptive refinement) for shapes of any subdivision scheme -- now that Loop and Bilinear are fully supported.  So any remaining Catmark-specific assumptions or restrictions were removed and remaining legitimate limitations (e.g. lack of support for Bilinear in glPaintTest or Loop in glPtexViewer) were emphasized with specific error messages and/or assertions.
Usage of all examples was also made more consistent -- particularly the loading of Obj files from the command line.  Conventions adopted from existing usage include:
- Obj files specified on the command line require a .obj suffix
- shapes from Obj files are assigned the …
=> Several minor updates to the GL examples

opensubdiv/far/patchBasis.cpp, opensubdiv/osd/patchBasisCommon.h
Correcting the logic introduced recently in #1055 for patches with two boundary edges.
=> Correction to minor changes to BoxSplineTri boundary computation

examples/glFVarViewer/glFVarViewer.cpp, examples/glFVarViewer/init_shapes.h
This change adds options for smooth corner, single crease and inf-sharp patches to the glFVarViewer in the same layout as they appear in the glViewer.  The inf-sharp patch option is particularly warranted as some of the face-varying interpolation modes really warrant inf-sharp patches to capture the desired boundary shape, and results at low-levels of refinement can be misleading without them (though the poor approximation is correct).
=> Added options to glFVarViewer example consistent with glViewer

opensubdiv/osd/glslPatchCommon.glsl
The 1st order Taylor approximation used to resolve degenerate normals in the GLSL Bezier triangle shader was copied from its use with quads.  It approximates in the direction of the patch interior, but detecting the upper U and V patch extremities of the unit square for quads is not sufficient for triangles -- the diagonal boundary (where u + v == 1) also needs to be considered and the derivative terms negated accordingly.
=> Minor improvement to degenerate normals in GLSL Bezier triangle

cmake/FindDXSDK.cmake
- Add search path for Windows 10 support for DirectX SDK
- Turn off searching the default paths for the DirectX libraries and instead use the explicit paths provided.  On certain configurations, this fixes the case where cmake will pick up the librariees for the wrong architecture
- Be more explicit when a required DirectX library is not found instead of silent failure.
=> Add support for newer DirectX SDKs

CMakeLists.txt
As mentioned in issue #997, OpenSubdiv still uses CUDA functionality that is being deprecated.  When warnings are treated as errors, this can make OpenSubdiv fail to compile.  For now, we turn off these
deprecation warnings until we can address them.
=> Turn off CUDA deprecation warnings until addressed

cmake/FindDocutils.cmake
On Windows we now look for and use an explicit python interpreter to find the version of docutils installed.  There is more information in the commit, but it would result in a much cleaner change if we could decide that it's okay to do this for all platforms.  For now, just do it for Windows to get us unblocked.
=> Allow using docutils on Windows

build_scripts/build_osd.py
The build script assumed that we always had ZLIB, but we only add it when we build ptex.  Instead of removing it on Linux, we now only add it when we need to on non-Linux platforms.
=> Fix build script on Linux when not building ptex

CMakeLists.txt
The example code that uses Metal forces C++11 features, therefore we have to turn it on clang so that we can enable the building of compatible code that can be used by Metal and GL at the same time.
=> Turn on C++11 in clang when building with Metal

examples/mtlPtexViewer/CMakeLists.txt, examples/mtlViewer/CMakeLists.txt
This fixes the build when trying to build both the Metal examples and the GL examples in the same build. The change is an unfortunate consequence of how dependencies are bundled together in examples/common and a future task is needed to split up these dependencies.  The same workaround exists in the DirectX examples as well and would also benefit from splitting up the dependencies.
=> Fix build of Metal examples when also building GL

examples/mtlPtexViewer/OSX/Info.plist, examples/mtlPtexViewer/OSX/MainMenu.xib, examples/mtlViewer/OSX/Info.plist, examples/mtlViewer/OSX/MainMenu.xib
- Renamed the default "NewApplication" in menus to the real name of the app
- Fixed copyright information in the "About" dialog.
=> Mostly cosmetic clean up to the Metal example apps

tutorials/far/CMakeLists.txt, tutorials/far/tutorial_0/CMakeLists.txt, tutorials/far/tutorial_1/CMakeLists.txt, tutorials/far/tutorial_10/CMakeLists.txt, tutorials/far/tutorial_2/CMakeLists.txt, tutorials/far/tutorial_3/CMakeLists.txt, tutorials/far/tutorial_4/CMakeLists.txt, tutorials/far/tutorial_5/CMakeLists.txt, tutorials/far/tutorial_6/CMakeLists.txt, tutorials/far/tutorial_7/CMakeLists.txt, tutorials/far/tutorial_8/CMakeLists.txt, tutorials/far/tutorial_9/CMakeLists.txt
Most of the tutorials are built and installed the same way so provide a common _add_far_tutorial macro.
=> Clean up the CMakeLists.txt in the far tutorials

opensubdiv/osd/hlslPatchCommon.hlsl, opensubdiv/osd/hlslPatchGregoryBasis.hlsl
- Make sure to initialize all structs properly when using gregory patches
- Rename a loop variable to avoid shader compiler warning.
=> A few minor fixes for Gregory Patches in DirectX

tutorials/far/tutorial_1_1/far_tutorial_1_1.cpp, tutorials/far/tutorial_1_2/far_tutorial_1_2.cpp, tutorials/far/tutorial_2_1/far_tutorial_2_1.cpp, tutorials/far/tutorial_2_2/far_tutorial_2_2.cpp, tutorials/far/tutorial_2_3/far_tutorial_2_3.cpp, tutorials/far/tutorial_4_1/far_tutorial_4_1.cpp, tutorials/far/tutorial_4_2/far_tutorial_4_2.cpp, tutorials/far/tutorial_4_3/far_tutorial_4_3.cpp, tutorials/far/tutorial_5_1/far_tutorial_5_1.cpp, tutorials/far/tutorial_5_2/far_tutorial_5_2.cpp
The recent reorganization and renaming of Far tutorials (#1083) neglected to update references to the tutorials from within the source for the tutorials.  These changes correct that oversight.
While making these changes, comments using the old 2.x style class naming (e.g. FarClassName vs Far::ClassName) were also encountered and the class names updated.
=> Fixed references to recently renamed tutorials in tutorial source

documentation/compatibility.rst, documentation/far_overview.rst, documentation/hbr_overview.rst, documentation/osd_overview.rst, documentation/porting.rst, documentation/release_31.rst, documentation/subdivision_surfaces.rst, documentation/using_osd_hbr.rst
Recent changes to the documentation have been made consistent in terms of internal links, but changes to subsections and their titles have broken pre-existing external links to those sections.  These changes restore some subsection titles and rename explicit internal targets to preserve those external links (which include several in the USD code base and examples).
=> Minor documentation changes to preserve existing external links

documentation/code_examples.rst, documentation/glviewer.rst, examples/common/argOptions.cpp, examples/common/argOptions.h, examples/common/viewerArgsUtils.cpp, examples/dxViewer/dxviewer.cpp, examples/glFVarViewer/glFVarViewer.cpp, examples/glViewer/glViewer.cpp
These changes replace the poorly named -axis flag (used by the viewing applications and recently included in the set of common command line arguments) with -yup.  The default viewing orientation for all examples is Z-axis up and the -yup flag now modifies the viewing matrix -- not the shape coordinates -- to present the initial view with Y-axis up.
=> Replaced -axis with -yup in example viewers and common args

opensubdiv/far/topologyRefiner.cpp
This change adds newly required feature isolation for the single-crease patch that is now necessary in the absence of the previous boundary isolation for quads (removed in #1025).
When the single-crease patch option is used without the inf-sharp patch option, semi-sharp single-crease patches are intended to approximate interior inf-sharp edges.  When too many inf-sharp features (including boundaries) are present around a base face, despite the face being regular and easily and accurately represented with a single regular patch, isolation is required if any of the inf-sharp edges are interior edges to accommodate the single-crease patch approximation.
=> Fixed single-crease patch creation near unisolated boundaries

documentation/glevallimit.rst, documentation/glpainttest.rst, documentation/glptexviewer.rst, documentation/glstencilviewer.rst, examples/common/viewerArgsUtils.cpp, examples/common/viewerArgsUtils.h, examples/glEvalLimit/glEvalLimit.cpp, examples/glImaging/glImaging.cpp, examples/glPaintTest/glPaintTest.cpp, examples/glPtexViewer/glPtexViewer.cpp, examples/glShareTopology/glShareTopology.cpp, examples/glStencilViewer/glStencilViewer.cpp
These changes update the remaining GL examples to make use of the common command line argument parsing and utilities recently added in #1087.  All now make use of common argument parsing and loading of user specified geometry.  Viewers that accept user-specified geometry were also updated to implement the -yup option consistently.
A couple of examples received some extra work:  glEvalLimit had additional UI options added to make it more consistent with glViewer, and glPtexViewer was updated to make use of the common ObjAnim class to support loading and interpolation of animated sequences of Obj files.
=> Updated GL examples for common command line arguments

README.md
This change aims to help make the README more concise by having the hyperlinks combined with their respective text.
=> Combine Hyperlink and Lib Name

opensubdiv/far/catmarkPatchBuilder.cpp, opensubdiv/far/loopPatchBuilder.cpp
This change fixes an uncommon bug that occurs when building a patch from a face when both ends of an interior edge are infinitely sharp.  In this case, the stencil size of the interior face-points was not correctly estimated and triggers an assertion.
This can show up when vertices are implicitly made inf-sharp, e.g. when vertices are non-manifold or when boundary vertices in face-varying space are sharpened according to the interpolation choice.
=> Fixed patch construction bug with sharp corner patches

opensubdiv/far/patchBuilder.cpp
This change fixes a regression that was introduced into the application of the legacy patch construction option that approximates a smooth corner patch with a regular sharp patch.  The condition of application had been rewritten and mistakenly considered all corners, rather than only those that had been determined as smooth.  So some sharp corners were being mistakenly re-assigned as smooth.
This tended to occur more frequently in face-varying patches, where the combination of inf-sharp and irregular features on boundaries is more prevalent along the UV seams.
=> Fixed regression with legacy smooth corner patch approximation

opensubdiv/vtr/fvarLevel.cpp, opensubdiv/vtr/fvarLevel.h
This change fixes an obscure bug present since 3.1 when face-varying patches and the inf-sharp patch option were introduced.  Semi-sharp features on the seams of face-varying patches were mistakenly tagged as inf-sharp, which only took effect when the inf-sharp patch option was enabled.
=> Fixed semi-sharp face-varying boundaries when creating inf-sharp patches

opensubdiv/far/patchTableFactory.cpp, opensubdiv/osd/glslPatchBSpline.glsl, opensubdiv/osd/glslPatchBoxSplineTriangle.glsl, opensubdiv/osd/glslPatchCommon.glsl, opensubdiv/osd/glslPatchCommonTess.glsl, opensubdiv/osd/glslPatchGregory.glsl, opensubdiv/osd/glslPatchGregoryBasis.glsl, opensubdiv/osd/glslPatchGregoryTriangle.glsl, opensubdiv/osd/hlslPatchBSpline.hlsl, opensubdiv/osd/hlslPatchBoxSplineTriangle.hlsl, opensubdiv/osd/hlslPatchCommon.hlsl, opensubdiv/osd/hlslPatchCommonTess.hlsl, opensubdiv/osd/hlslPatchGregory.hlsl, opensubdiv/osd/hlslPatchGregoryBasis.hlsl, opensubdiv/osd/hlslPatchGregoryTriangle.hlsl, opensubdiv/osd/mtlPatchBSpline.metal, opensubdiv/osd/mtlPatchBoxSplineTriangle.metal, opensubdiv/osd/mtlPatchCommon.metal, opensubdiv/osd/mtlPatchCommonTess.metal, opensubdiv/osd/mtlPatchGregory.metal, opensubdiv/osd/mtlPatchGregoryBasis.metal, opensubdiv/osd/mtlPatchGregoryTriangle.metal
Since 3.1 it has been possible to restrict the level of refinement around extraordinary vertices such that a resulting Gregory patch might have transitional edges, but the existing tessellation shaders for Gregory basis and Legacy Gregory patches had not been updated to account for this situation.
These changes make the handling of the tessellation of transitional edges more consistent across all of the back-end drawing implementations for all patch types along with improving some other minor discrepancies among the various shader implementations.
=> Gregory patch transitional edge tessellation

opensubdiv/far/patchTable.h, opensubdiv/far/patchTableFactory.cpp, opensubdiv/far/patchTableFactory.h
These changes modify a couple of public methods added to Far to support variable precision based on feedback.  Methods to query the precision of Far::PatchTable's internal StencilTables were renamed, along with the precision related members of Far::PatchTableFactory::Options.
=> Minor revisions to a few precision related methods of Far classes

opensubdiv/osd/glslPatchCommon.glsl, opensubdiv/osd/patchBasisCommon.h
Several of the methods in osd/patchBasisCommon.h were
never intended as public API, and several have been
deprecated in favor of the newer OsdEvaluatePatchBasis()
and OsdEvaluatePatchBasisNormalized() methods. These
obsolete methods have now all be marked as deprecated.
Also, fixed a minor spelling typo in glslPatchBasisCommon.glsl
=> Minor revisions to some Osd deprecation notes

examples/dxViewer/init_shapes.h, examples/glFVarViewer/init_shapes.h, examples/glViewer/init_shapes.h, examples/mtlViewer/init_shapes.h, regression/shapes/all.h, regression/shapes/loop_tetrahedron.h
A tetrahedron is added here to the set of test shapes for Loop.  An open tet (one face missing) and a tet with holes (the toroidal_tet) are already present, but a simple tetrahedron has been absent.
A second commit includes the new shape in the viewer examples for the main back-ends, along with the glFVarViewer for inspecting its assigned UVs.
=> Added simple tetrahedron to set of Loop test shapes

examples/dxPtexViewer/shader.hlsl, examples/dxViewer/shader.hlsl, examples/glFVarViewer/glFVarViewer.cpp, examples/glFVarViewer/shader.glsl, examples/glImaging/glImaging.cpp, examples/glImaging/shader.glsl, examples/glPtexViewer/glPtexViewer.cpp, examples/glPtexViewer/shader.glsl, examples/glShareTopology/glShareTopology.cpp, examples/glShareTopology/shader.glsl, examples/glViewer/glViewer.cpp, examples/glViewer/shader.glsl
These improve some of the example shader code related to
adaptive refinement and tessellation of Loop meshes.
The main change is to update shader configuration so that it
depends only on the resulting patch type. Previously, there
were cases where a "LOOP" preprocessor symbol was passed
from the application to the shader code, but this is error prone
and confusing.
Also, fixed a few minor bugs discovered during testing.
=> Minor improvements to examples for Loop

opensubdiv/far/patchBuilder.cpp
This change addresses discontinuities that appear between face-varying patches for Loop when using the LINEAR_BOUNDARIES option.  The change works around a deeper issue in the way that face-varying topology is tagged for this option -- the boundary vertices are tagged as corners for ease of refinement and interpolation, but need to be re-assessed when considered as part of a patch.
=> Fixed cracks in face-varying Loop patches for lineaar-boundaries option

opensubdiv/far/patchMap.h, opensubdiv/far/patchTable.h, opensubdiv/far/patchTableFactory.h, opensubdiv/far/stencilTableFactory.h
These are very minor changes to Doxygen comments in Far header files based on feedback.  It also includes a fix to Doxygen warnings generated by far/patchTable.h and its use of \<REAL\> in the comments.
=> Minor improvements to Doxygen comments in Far header files

examples/glPaintTest/glPaintTest.cpp
The fixed brush size of 500 pixels in examples/glPaintTest wasn't very effective in demonstrating its effects.  These changes set the default brush size to a more reasonable 100 pixels and add a slider to modify the brush size interactively.
=> Improved examples/glPaintTest with slider to modify brush size

documentation/release_34.rst, documentation/release_notes.rst
Changes here include an update to the 3.4 release notes page that includes a little more detail, and a change to the Release Notes summaries to organize them into sections for a more structured table of contents.
=> Minor updates to release notes pages

documentation/far_overview.rst, documentation/osd_overview.rst, documentation/osd_shader_interface.rst
Updated the Far Overview and Osd Overview and shader
interface pages for 3.4 to include a discussion of
trianglular patch types and other minor updates.
=> Updated Far and Osd user guide docs for 3.4

opensubdiv/osd/mtlComputeKernel.metal
Fixed the initialization of patchArray and patchParam
in the implementation of the MTLComputeEvaluator::EvalPatches()
compute kernel.
=> Fixed regression in MTLComputeEvaluator

examples/mtlViewer/iOS/ViewController.mm, examples/mtlViewer/mtlViewer.h, examples/mtlViewer/mtlViewer.mm
-Fixed the iOS ViewController to set the correct irregular
patch approximation mode.
-Fixed the setting of fractionalSpacing to be separate from
screenspace tessellation.
-Fixed the configuration of the internal stage-in setting
on embedded builds.
=> Fixed mtlViewer for iOS

documentation/subdivision_surfaces.rst
Minor changes to the "Subdivision Surfaces" documentation page here include:  fixing a broken HTML link, emphasizing the requirement that Loop meshes be purely triangular and removing a note listing pre-3.4 limitations of Loop functionality.
=> Minor improvements to the introductory documentation

documentation/far_overview.rst
These changes improve the section on Patch Parameterization in the Far Overview to illustrate the quadrangulation of non-quad faces and the offset indices that result -- requiring the use of Far::PtexIndices.
=> Improved Far patch parameterization documentation for non-quads

examples/common/hud.h, examples/glPaintTest/glPaintTest.cpp
These changes fix warnings generated from MSVC in the OpenGL examples (noted in #1156) as well as new warnings arising from MSVC 2019.
=> Fixed Microsoft Visual Studio warnings in examples

examples/common/CMakeLists.txt, examples/common/viewerArgsUtils.cpp, examples/common/viewerArgsUtils.h, examples/dxViewer/dxviewer.cpp, examples/glEvalLimit/glEvalLimit.cpp, examples/glFVarViewer/glFVarViewer.cpp, examples/glImaging/glImaging.cpp, examples/glPaintTest/glPaintTest.cpp, examples/glPtexViewer/glPtexViewer.cpp, examples/glShareTopology/glShareTopology.cpp, examples/glStencilViewer/glStencilViewer.cpp, examples/glViewer/glViewer.cpp, examples/mtlPtexViewer/mtlPtexViewer.mm, examples/mtlViewer/mtlViewer.mm, regression/common/CMakeLists.txt, regression/common/arg_utils.cpp, regression/common/arg_utils.h
These changes move the ArgOptions class for parsing common command line arguments from examples/common to regression/common.  This allows it to be used in regression tests and tutorials without creating the link dependencies that examples/common introduces (e.g. osdGPU, Ptex, etc.).
=> Moved common command line parsing to regression/common

examples/dxViewer/init_shapes.h, examples/farViewer/init_shapes.h, examples/glEvalLimit/init_shapes.h, examples/glFVarViewer/init_shapes.h, examples/glImaging/init_shapes.h, examples/glPaintTest/init_shapes.h, examples/glShareTopology/init_shapes.h, examples/glStencilViewer/init_shapes.h, examples/glViewer/init_shapes.h, examples/mtlViewer/init_shapes.h
As a follow-up to #1170, this change adds the new test shapes created for the boundary interpolation case "none" to all of the interactive examples.
In order to keep the shapes lists from growing endlessly, some shapes that have recently been made redundant by improvements to others were removed to partially offset the additions.
=> Updated examples with new boundary interpolation test shapes

examples/dxPtexViewer/sky.cpp, regression/common/arg_utils.cpp, regression/common/arg_utils.h
This fixes some warnings raised by recent Visual Studio versions.
=> Fixed warnings in examples and regression/common

cmake/FindDXSDK.cmake, cmake/FindGLEW.cmake, cmake/FindTBB.cmake
For Visual Studio 2019 the target architecture is specified
separately from the generator, and this updates the cmake
modules to be able to locate libraries for the correct target.
Also, makes use of CMAKE_VS_WINDOWS_TARGET_PLATFORM_VERSION
to be able to use the correct Windows Kit when multiple
tool sets and development kits are available.
=> Updated cmake/Find* modules for VS2019

examples/common/CMakeLists.txt, examples/dxPtexViewer/CMakeLists.txt, examples/glPtexViewer/CMakeLists.txt, examples/mtlPtexViewer/CMakeLists.txt, opensubdiv/CMakeLists.txt
Removed the link dependency from libosd to
the Ptex library since Ptex is used only by the
examples. Updated examples/common to separate
the common Ptex sources from the other common
sources so that they are used only by the Ptex
examples.
=> Fixed Ptex link dependencies

tutorials/far/tutorial_5_2/far_tutorial_5_2.cpp
The main change here fixes a memory leak when an optional .obj file was specified.  Given this tutorial was written with parameters to illustrate time versus space trade-offs, a memory leak here is potentially more of an issue than in others.
Other minor changes were applied while updating the source: command line parsing was updated to use tools in regression/common, and line-wrapping and indentation were updated to conform to standards.
=> Fixed memory leak in far/tutorial_5_2 with optional .obj file

documentation/CMakeLists.txt, documentation/tutorials.rst, tutorials/far/tutorial_5_3/CMakeLists.txt, tutorials/far/tutorial_5_3/far_tutorial_5_3.cpp
Example usage of Far::LimitStencilTable was added in tutorials/far/tutorial_5_3.  Stencils for limit points of a crude tessellation of a shape are computed and applied to a series of translated poses of that shape.
Since LimitStancilTables require understanding of patches and PatchTables, it was added to the 5.x tutorials that cover PatchTables rather than the 4.x tutorials that cover StencilTables.
=> Added new tutorial for Far::LimitStencilTable

tutorials/far/tutorial_5_1/far_tutorial_5_1.cpp
Prior to the release of 3.4, the newly added Far::PatchTableFactory method to derive adaptive refinement options from patch table options was illustrated in far/tutorial_5_1.  But the desired refinement level was not being used to initialize the patch options.  As a result, the default value of 10 was being used to initialize adaptive refinement options.
The changes here initialize the patch options with the desired level and include a comment to warn about this kind of oversight in future.
=> Fixed initialization oversight in far/tutorial_5_1

examples/common/CMakeLists.txt, examples/dxPtexViewer/CMakeLists.txt, examples/dxViewer/CMakeLists.txt, examples/farViewer/CMakeLists.txt, examples/glEvalLimit/CMakeLists.txt, examples/glFVarViewer/CMakeLists.txt, examples/glImaging/CMakeLists.txt, examples/glPaintTest/CMakeLists.txt, examples/glPtexViewer/CMakeLists.txt, examples/glShareTopology/CMakeLists.txt, examples/glStencilViewer/CMakeLists.txt, examples/glViewer/CMakeLists.txt, examples/mtlPtexViewer/CMakeLists.txt, examples/mtlViewer/CMakeLists.txt
Split the examples/common objects into graphics API dependent object
libraries (following the pattern used for cemmon Ptex dependencies)
so that DX11 and Metal examples are no longer forced to link with GLFW.
=> Fixed examples link dependency on GLFW

cmake/FindDXSDK.cmake, examples/dxPtexViewer/dxPtexViewer.cpp, examples/glPtexViewer/glPtexViewer.cpp
Fixed a few issues discovered while testing:
- updated dxPtexViewer to use regression/arg_utils and examples/objAnim
- fixed a memory allocation bug in glPtexViewer that was crashing on debug builds
- fixed a recently introduced typo in FindDXSDK.cmake
=> Updates to GL and DX PtexViewers

examples/common/glHud.cpp
This typo was in code that was executed only on platforms
with older GL header versions, or without using a GL loader
like GLEW.
=> Fixed a typo in examples/common/glHud.cpp

CMakeLists.txt
Fixes warnings from CMake versions 3.1 and later. Tested back through CMake 2.8
=> Fixed CMP0054 warnings in top-level CMakeLists.txt

opensubdiv/vtr/fvarLevel.cpp, opensubdiv/vtr/fvarLevel.h, opensubdiv/vtr/level.h
Minor update to the implementation of a few internal tagging
methods in Vtr to avoid violating strict-aliasing rules.
Specifically, switched to using std::memcpy instead of
reinterpret_cast to implement type punning.
=> Fixed strict-aliasing warnings

tutorials/far/CMakeLists.txt, tutorials/far/tutorial_1_1/CMakeLists.txt, tutorials/far/tutorial_1_2/CMakeLists.txt, tutorials/far/tutorial_2_1/CMakeLists.txt, tutorials/far/tutorial_2_2/CMakeLists.txt, tutorials/far/tutorial_2_3/CMakeLists.txt, tutorials/far/tutorial_3_1/CMakeLists.txt, tutorials/far/tutorial_4_1/CMakeLists.txt, tutorials/far/tutorial_4_2/CMakeLists.txt, tutorials/far/tutorial_4_3/CMakeLists.txt, tutorials/far/tutorial_5_1/CMakeLists.txt, tutorials/far/tutorial_5_2/CMakeLists.txt, tutorials/far/tutorial_5_3/CMakeLists.txt
This adds an "osd" prefix to the macros used
to install far tutorials.
Fixes #1157
=> Prefix remaining OpenSubdiv CMake macros

cmake/FindTBB.cmake
We no longer search for or link with several TBB libraries
which are not used by this code base. Specifically, we no
longer link with tbbmalloc, tbbmalloc_debug, tbbmalloc_proxy
tbbmalloc_proxy_debug, tbb_preview, and tbb_preview_debug.
Fixes #1064
=> Removed linking with unnecessary TBB libraries

CMakeLists.txt, opensubdiv/CMakeLists.txt
This adds support for the standard global option
BUILD_SHARED_LIBS
to select whether to build shared libraries.
Note that building shared DLL libraries is still
not yet supported on Windows.
Fixes #1169
=> Added option to control building shared libraries

azure-pipelines.yml
Updated platform requirements to Ubuntu 18.04, macOS 10.14,
and Windows 2019. And added execution of CTest tests and
publishing of test results.
=> Updated Azure Pipelines script

build_scripts/build_osd.py
Updated build_osd.py for VS2019
Support setting the generator platform (-A)
when building with Visual Studio 2019 as well
as detecting VS2019 availability.
Fixed-up EOL whitespace and typos in build_osd.py
Removed GLEW from build_osd.py
=> Updated build_osd.py for VS2019 and GLEW

CMakeLists.txt, glLoader/CMakeLists.txt, opensubdiv/CMakeLists.txt
Changed the glLoader library to an object library
instead of a static library to improve generating
opensubdiv static libraries.
=> Fixed static library linking on Windows

CMakeLists.txt, opensubdiv/CMakeLists.txt
Updated to link the GL loader objects directly
along with the osd GPU objects for both static
and dynamic libraries.
=> Additional fixes for dynamic and static linking
