opensubdiv/osd/glslPatchGregory.glsl
opensubdiv/osd/hlslPatchGregory.hlsl

- reduces instruction count by ~1/5
- improves readability

Minor gregory patch shader optimizations

---

README.md
documentation/far_overview.rst

Pointing the README build notes to the public web site so there is a single
source of build documentation.
Fixed minor typo in far_overview.

Updating documentation in readme and far_overview.

---

examples/common/patchColors.cpp
examples/glPtexViewer/glPtexViewer.cpp
examples/glPtexViewer/shader.glsl
examples/glViewer/glViewer.cpp
examples/glViewer/shader.glsl
opensubdiv/far/patchDescriptor.cpp
opensubdiv/far/patchDescriptor.h
opensubdiv/far/patchParam.h
opensubdiv/far/patchTables.h
opensubdiv/far/patchTablesFactory.cpp
opensubdiv/far/patchTablesFactory.h
opensubdiv/osd/d3d11DrawRegistry.cpp
opensubdiv/osd/drawContext.cpp
opensubdiv/osd/drawContext.h
opensubdiv/osd/glDrawRegistry.cpp
opensubdiv/osd/glslPatchBSpline.glsl
opensubdiv/osd/glslPatchCommon.glsl
opensubdiv/osd/glslPatchGregory.glsl
opensubdiv/osd/glslPatchGregoryBasis.glsl
opensubdiv/osd/glslPatchTransition.glsl

Changed shader based patch drawing code to support drawing various bspline patch configurations with a single shader configuration and single draw call.

Unified adaptive patch drawing

---

tutorials/far/tutorial_6/far_tutorial_6.cpp

following recent API changes, specifiy endcap factory.

Fixes far_tutorial_6 crash

---

.travis.yml
CMakeLists.txt
examples/glImaging/CMakeLists.txt
regression/osd_regression/CMakeLists.txt

-add .travis.yml
-NO_GLTESTS option to cmakefile for headless testing

Travis CI configuration

---

.travis.yml

(also triggerring the first test build)

Add some comments into .travis.yml

---

examples/dxPtexViewer/shader.hlsl
examples/dxViewer/dxviewer.cpp
examples/dxViewer/shader.hlsl
examples/glPtexViewer/shader.glsl
examples/glViewer/glViewer.cpp
examples/glViewer/shader.glsl
opensubdiv/osd/glslPatchBSpline.glsl
opensubdiv/osd/glslPatchGregory.glsl
opensubdiv/osd/glslPatchGregoryBasis.glsl

Also made a couple minor changes to true up the GLSL patch shaders.

Fixed example code use of single crease patches

---

opensubdiv/far/interpolate.cpp

This is an interim improvement for the computation of Gregory patch derivatives, pending the upcoming work to support higher-order derivatives.  It fixes a normalization bug with the (s,t) coordinate and includes an implementation of the true derivatives for future reference (excluded with #ifdef for now).
Far::GetGregoryWeights() has not yet been incorporated into other evaluation methods, so this shouldn't change any runtime behavior.

Refactored Far computation of Gregory patch basis functions:

---

examples/farViewer/farViewer.cpp

Fixed a simple crash in farViewer when not using adaptive.
Also snuck in a small code clean up.

Fixed crash in farViewer when not using Adaptive.

---

opensubdiv/osd/glslPatchGregory.glsl
opensubdiv/osd/glslPatchGregoryBasis.glsl
opensubdiv/osd/hlslPatchGregory.hlsl
opensubdiv/osd/hlslPatchGregoryBasis.hlsl

There was an unnecessary double-flip in the shading calculations.

Fixed handedness flip in Gregory{Basis} shaders

---

opensubdiv/osd/glslPatchBSpline.glsl
opensubdiv/osd/glslPatchCommon.glsl
opensubdiv/osd/glslPatchGregory.glsl
opensubdiv/osd/glslPatchGregoryBasis.glsl
opensubdiv/osd/hlslPatchBSpline.hlsl
opensubdiv/osd/hlslPatchCommon.hlsl
opensubdiv/osd/hlslPatchGregory.hlsl
opensubdiv/osd/hlslPatchGregoryBasis.hlsl

Cleaned up the Legacy Gregory shader source by accessing buffer
data through helper functions.
Switched to performing tessellation in untransformed (object) space.

Sync'ed up GLSL and HLSL patch shader source.

---

examples/mayaPolySmooth/mayaPolySmooth.cpp

Fixing some minor fallout after merging #514.

Fix MayaPolySmooth example

---

opensubdiv/far/CMakeLists.txt
opensubdiv/far/stencilBuilder.cpp
opensubdiv/far/stencilBuilder.h
opensubdiv/far/stencilTable.cpp
opensubdiv/far/stencilTable.h

* Added stencilTable.cpp
* Fixed the "off" variable shadow warning
* Moved constructors to cpp file
* Made LimitStencilTable constructor private
* other minor clean up.

Add stencilTable.cpp, minor cleanup

---

tutorials/far/tutorial_6/far_tutorial_6.cpp

Removed unneeded use of end cap factory in far_tutorial_6.

Small update to far_tutorial 6.

---

tutorials/far/tutorial_6/far_tutorial_6.cpp

Although the PatchTable interpolation API is still somewhat working in progress,
this change fixes the breakage of extraordinary vertices evaluation in this tutorial code.

Fix far_tutorial_6 to use gregory basis endcaps.

---

opensubdiv/far/topologyRefinerFactory.cpp

Unlike the "edge only" or "edge and corner" modes, the boundary interpolation mode "none" is much less practical and rarely used.  Making proper use of it with Hbr was non-obvious as performing simple uniform refinement on Hbr would lead to incorrect interpolation -- underweighted vertices pulled toward the origin.  The same was true in Far until we sharpened the edges in this case too -- making it effectively the same as "edge only".  From Takahito's comparisons with RenderMan, its clear that it uses Hbr to achieve the desired effect of boundary faces being invisible and only supporting the limit of interior faces, so we need to do something else here.
So to make the existing refinement operations achieve this, we simply tag the boundary faces as holes and leave it to Uniform or Adaptive …

Fixed refinement when using BoundaryInterpolation mode "None"

---

examples/glFVarViewer/glFVarViewer.cpp
opensubdiv/far/patchTableFactory.cpp

This fixes a couple of minor regressions with linear FVar
display in the glViewer and glFVarViewer.

Fixed a couple of problems with FVar handling

---

examples/glViewer/glViewer.cpp
examples/glViewer/shader.glsl

- split displayStyle and shadingMode control into two different settings.
- add more shadingModes:
normal, curvature(screen space), curvature (from patch)
- minor cleanup

glViewer: separate displayStyle(wire) and shading.

---

examples/glFVarViewer/glFVarViewer.cpp
examples/glFVarViewer/shader.glsl
examples/glViewer/glViewer.cpp
examples/glViewer/shader.glsl

Renamed the shader define used by the glViewer and glFVarViewer to
make the intended use more clear and robust.

Fixed face varying shading for examples

---

opensubdiv/osd/glslPatchCommon.glsl
opensubdiv/osd/hlslPatchCommon.hlsl

The tess factor of transition edges has to be clamped to 2.

Fix tessellation cracks when screen space tesselation is turned off.

---

opensubdiv/far/topologyLevel.h
opensubdiv/far/topologyRefiner.h
opensubdiv/far/topologyRefinerFactory.h

Added Doxygen tags to some Far headers

---

examples/dxViewer/dxviewer.cpp
examples/dxViewer/shader.hlsl
examples/glViewer/glViewer.cpp
examples/glViewer/shader.glsl

delete debugging display modes from glViewer.

example fix: remove unnecessary debugging feature.

---

documentation/release_notes.rst
opensubdiv/version.h

- changed the namespace version
- updated release notes documentation

Getting ready for RC1.

---

documentation/release_notes.rst

Added more detail about specific awesomenesses.

Updated RC1 release notes

---

documentation/release_notes.rst
documentation/subdivision_surfaces.rst

This takes care of some of the remaining "Beta issues" that have either been dealt with or deferred.

Minor revisions to documentation files

---

documentation/far_overview.rst
documentation/osd_overview.rst

- Make our intentions about Face-varying support clear.
- Remove outdated "Patch Transitions" section.
- Remove outdated Beta note regarding control vertices ordering.

A few small updates to the docs.

---

tutorials/far/tutorial_3/far_tutorial_3.cpp

In Far_Tutorial_3: Added vertex colors to a second FVarChannel channel. The example will then interpolate these new values and print them to the console so it is simpler to check that when we have different channels interpolation still works.

Far_Tutorial_3 : Added vertex colors to the second face-varying channel

---

documentation/CMakeLists.txt
documentation/nav_template.txt
documentation/porting.rst

This document is a work in progress with some sections left incomplete for other
developers to fill in.

Added porting guide to public documentation

---

examples/mayaPolySmooth/mayaPolySmooth.cpp

The Maya plugin now reads the first UV channel and the first vertex color channel and it passes it to OpenSubdiv for interpolation. When that is done, it inserts the data back into the Maya mesh.

The Maya plugin can interpolate UVs and Vertex color channels.

---

documentation/porting.rst

Adding a chunk of documentation to the porting page -- mainly the construction of TopologyRefiner now required instead of HbrMesh<T>.
I'm not very familiar with RST, so if someone sees places where links to examples, Doxygen or anything else would be useful here, please add them.  Thanks

Added more content to the docs for porting and compatibility

---

documentation/CMakeLists.txt
documentation/intro_30.rst
documentation/nav_template.txt
documentation/release_notes.rst

Modified Release Notes to be a brief overview of the 3.0 release
features, while moving the descriptive text to a new section that
outlines the major changes in 3.0 grouped along with the Porting
Guide and Subdivision Compatibility document.

Reorganized Release Notes

---

documentation/CMakeLists.txt

remove using_osd_compile.rst from CMakeLists.txt

fix document build

---

documentation/compatibility.rst
documentation/porting.rst
documentation/release_notes.rst
documentation/subdivision_surfaces.rst
opensubdiv/sdc/options.h

This includes a few documentation files that are in progress -- I don't want to check in everything at the last minute.

A few incremental updates to a number of documentation pages

---

documentation/intro_30.rst
documentation/nav_template.txt

- Renamed nav bar title to 'Release 3.0' to match document.
- Minor tweaks and typo fixes.

Minor changes to intro_30.rst

---

documentation/compatibility.rst

Applied some minor tweaks to the Compatibility page as suggested.

Improvements to the Compatibility doc page

---

documentation/CMakeLists.txt
documentation/contributing.rst
documentation/hedits.rst
documentation/intro.rst
documentation/nav_template.txt

This is a good start, but more could be done to make it even more useful for
developers.
* Updated nav_template to include contributing
* Removed contributing from intro
* Fixed RST compiler error in hedits
* Renamed "OpenSubdiv" header in nav to "OpenSubdiv User Guide"

Added "contributing" doc + minor doc cleanup

---

documentation/api_overview.rst
documentation/far_overview.rst
documentation/osd_overview.rst
documentation/sdc_overview.rst
documentation/vtr_overview.rst

add some links to deeper sections in api_overview
remove tiny api_layer images

minor update in overview pages

---

documentation/CMakeLists.txt
documentation/intro.rst
documentation/nav_template.txt
documentation/references.rst

- Added new references section for folks wishing to learn more about
subdivision.
- Fixed a reference in the intro.
- Fixed a minor typo in the nav bar.

Added references section to the documentation

---

examples/dxPtexViewer/dxPtexViewer.cpp
examples/dxViewer/dxviewer.cpp
examples/glPtexViewer/glPtexViewer.cpp
examples/glViewer/glViewer.cpp

Fractional tessellation is not currently supported by the core
tessellation shaders. This will be fixed in a future release.

Disabled Fractional Spacing toggles from viewers

---

documentation/release_notes.rst

Some of these items are better considered as minor, pro-active changes
rather than bug fixes.

Re-categorized some items in release notes

---

examples/dxPtexViewer/dxPtexViewer.cpp
examples/dxViewer/dxviewer.cpp
examples/glPtexViewer/glPtexViewer.cpp
examples/glViewer/glViewer.cpp
opensubdiv/osd/glslPatchCommon.glsl
opensubdiv/osd/hlslPatchCommon.hlsl

Restored support for Fractional tessellation

---

examples/farViewer/farViewer.cpp
examples/glStencilViewer/glStencilViewer.cpp
opensubdiv/osd/d3d11VertexBuffer.cpp

Re-submitting this for Manuel with my suggested edit.

Fixed build warnings (VS2015)

---

examples/common/hud.cpp
examples/common/hud.h

- Capping was broken (thanks to fakebits for pointing it out).  Fixes #801.
- Slides where min != 0 were also broken.

Fixed two issues with HUD sliders.

---

README.md
examples/common/glHud.cpp
examples/farViewer/farViewer.cpp
examples/farViewer/gl_fontutils.cpp
examples/farViewer/gl_mesh.cpp
examples/glEvalLimit/glEvalLimit.cpp
examples/glFVarViewer/glFVarViewer.cpp
examples/glImaging/glImaging.cpp
examples/glPaintTest/glPaintTest.cpp
examples/glShareTopology/glShareTopology.cpp
examples/glStencilViewer/glStencilViewer.cpp
examples/glViewer/glViewer.cpp
opensubdiv/osd/cpuGLVertexBuffer.cpp
opensubdiv/osd/glLegacyGregoryPatchTable.cpp
regression/osd_regression/main.cpp

Renaming and, or, and not et. al for the GLEW and GLFW projects. Ref #779

iso-646 fix for GLEW and GLFW projects

---

README.md
appveyor.yml

- Initial attempt to get AppVeyor (Windows CI) running on OpenSubdiv
- Initial support is bare-minimum, i.e., no OpenGL, no OpenCL, CUDA, TBB, etc..

Add appveyor support for OpenSubdiv

---

opensubdiv/vtr/level.cpp

At the time the original single-crease patch test was written, the tags for vertices were still evolving.  The vertex tags (VTags) were specifically designed to be bitwise combined so that the combined result of the corners of a face could be used to quickly deduce properties relevant to patches.  In this case we can get almost everything we need from the four corner tags without any topology traversal.
I kept the new version functioning the same as the old, but the context in which this test is usually run has the combined corner tags available and will already avoid many of the cases rejected here.  So there may eventually be merit in splitting this test in two:  the first working directly with available tags, the second inspecting sharpness values for the potential sharp edge of the …

Improved Vtr::Level::isSingleCreasePatch() test

---

opensubdiv/far/endCapBSplineBasisPatchFactory.cpp

With the recent addition of VSpans to indicate use of a partial ring around a vertex, the BSpline end cap factory code needed to be updated to defer to Gregory patches in more cases.  Boundary patches may now be created at interior vertices when the VSpan at a corner indicates a subset of the neighborhood is to be used.

Update BSpline end cap factory to detect partial rings at corners

---

opensubdiv/far/patchTableFactory.cpp

This set of changes updates Far::PatchTableFactory to optionally recognize and construct infinitely-sharp patches along infinitely-sharp creases.  Such patches will be either regular B-Spline boundary patches or irregular boundary patches, depending on the topology.  The "catmark_cube_creases2" is a good example.
This feature must currently be enable internally (pending decisions on the public API) and will benefit from forthcoming improvements, e.g. recognition during adaptive refinement to prevent over representation of regular patches.

Updated Far::PatchTableFactory to construct infinitely-sharp patches

---

opensubdiv/far/endCapBSplineBasisPatchFactory.cpp
opensubdiv/far/patchTableFactory.cpp
opensubdiv/far/topologyRefiner.cpp
opensubdiv/vtr/fvarLevel.h

This set of changes includes several independent bug fixes for special cases arising when enabling infinitely sharp patches.

A few bug fixes and minor improvements for inf-sharp patches

---

opensubdiv/far/patchBasis.cpp
opensubdiv/far/patchBasis.h
opensubdiv/far/patchDescriptor.h
opensubdiv/far/patchParam.h
opensubdiv/far/patchTable.cpp
opensubdiv/far/patchTable.h
opensubdiv/far/patchTableFactory.cpp
opensubdiv/osd/cpuEvaluator.cpp
opensubdiv/osd/ompEvaluator.cpp
opensubdiv/osd/tbbKernel.cpp

Also, added guards against empty containers to the
varying data accessors.

Added Far::PatchTable::GetVaryingPatchDescriptor()

---

opensubdiv/osd/cudaPatchTable.cpp
opensubdiv/osd/patchBasisCommon.h

- Fixed the size of a cudaMemcpy
- Fixed the use of local "static" storage

Fixed Osd::CudaEvaluator

---

examples/dxViewer/dxviewer.cpp
examples/dxViewer/shader.hlsl
examples/glViewer/glViewer.cpp
examples/glViewer/shader.glsl
opensubdiv/osd/mesh.h

These changes expose controls to enable
refinement and drawing of infinitely sharp
patches.

Updated DX/GL Viewers for Inf Sharp Patches

---

examples/glEvalLimit/glEvalLimit.cpp

Added a toggle to enable the use of infinitely sharp
patches and also implemented fitFrame ('f' keypress).

Updated glEvalLimit viewer for InfSharpPatch

---

examples/glStencilViewer/glStencilViewer.cpp

Added a toggle to enable the use of infinitely sharp
patches and also implemented fitFrame ('f' keypress).

Updated glStencilViewer for InfSharpPatches

---

opensubdiv/far/stencilTable.h

This fixes a couple of build warnings when running oxygen

Fixed LimitStencilTable.h doc for 2nd derivatives

---

examples/glFVarViewer/glFVarViewer.cpp
opensubdiv/far/patchTable.cpp
opensubdiv/far/patchTable.h
opensubdiv/far/patchTableFactory.cpp
opensubdiv/osd/clPatchTable.h
opensubdiv/osd/cpuPatchTable.cpp
opensubdiv/osd/cudaPatchTable.h
opensubdiv/osd/glPatchTable.h

Fixed some inconsistencies with the methods added
to support face-varying patches.

Addressed some FVar PatchTable API review notes

---

opensubdiv/far/patchTable.h
opensubdiv/far/patchTableFactory.h
opensubdiv/far/topologyDescriptor.h
opensubdiv/far/topologyLevel.h
opensubdiv/far/topologyRefiner.h

Made a few minor corrections for formatting and consistency issues while making a couple of other additions to Doxygen comments for a few Far classes.

Minor Doxygen additions and corrections to Far class headers

---

documentation/nav_template.txt
documentation/release_31.rst
documentation/release_notes.rst

- fixed dangling links to intro_30.html -- now release_30.html
- minor changes for consistency and to remove redundancy

Minor changes to 3.1 release documentation:

---

opensubdiv/osd/cpuKernel.cpp
opensubdiv/osd/glXFBEvaluator.cpp
opensubdiv/osd/ompEvaluator.cpp

Fixed a few bugs uncovered during testing.

Fixed Cpu Omp and GLXFB EvalStencils w/ deriv

---

opensubdiv/osd/CMakeLists.txt

Removed duplicate mtlVertexBuffer build config

---

opensubdiv/far/patchTableFactory.cpp

This change fixes a bug in face-varying patches for a Far::PatchTable that was constructed from uniform refinement.  The separate PatchParams for the face-varying patches (introduced in 3.1) were not being initialized, so the reparameterizations associated with the depth of the patches were not being computed correctly.

Fixed bug in face-varying patches of uniformly refined Far::PatchTable

---

opensubdiv/far/patchTableFactory.cpp

Previously, Far::PatchTableFactory::computePatchParam() was
considering all faces with a face vertex count != 4 as
irregular. This was incorrect for triangle refinement as
was the calculation of the UV subface parametric offsets for
triangle subfaces.
This is foundational work for implementing full support
for Loop scheme patch tables. This fix also allows correct
decoding of the parameter mapping for triangles resulting
from uniform refinement of Loop scheme meshes.
Fixes #962

Fixed computation of PatchParam for tri refinement

---

opensubdiv/far/catmarkPatchBuilder.cpp

The previous refactoring of Gregory patch construction (#966) replaced the inefficient accumulation of coefficients with direct assignment -- in all cases but one.  Since the 1-ring of a corner adjacent to a valence-2 interior corner actually overlaps itself, the accumulation was preserved in this case.  Support for this ended up littering the code with conditions specific to the valence-2 case -- complicating what should have been relatively simple assignment in the general case.
This change removes most of the invasive member variables and conditions associated with this case by allowing duplicate entries for the 1-rings to exist for a point, i.e. a row in the conversion matrix, but then accumulating them as a post-process only when a valence-2 interior vertex is present.  The same …

Simplify construction of Gregory patches with val-2 interior corners

---

opensubdiv/osd/cpuPatchTable.cpp

This change corrects the initialization of varying and face-varying patch arrays in Osd::CpuPatchTable.  All varying and face-varying arrays were previously initialized with the full patch count and zero offsets, rather than the count for the array's subset of patches with appropriate non-zero offsets from the buffer base.  The situation only occurs when using Gregory patches (a second array) for non-linear face-varying data.
This also corrects the related initialization of the face-varying PatchParam buffer noted in #955.

Corrected initialization of patch arrays in Osd::CpuPatchTable

---

opensubdiv/far/patchTableFactory.cpp

It's long been possible to generate true bicubic patches for a uniform subdivision level  with very little effort.  This change internally modifies the PatchTableFactory to conditionally generate such patches so that we can exercise the changes more thoroughly in testing while we consider how to expose the functionality.

Added internal support for non-linear uniform PatchTables

---

opensubdiv/far/stencilTableFactory.cpp

This set of changes fixes a couple of oversights introduced in #1012 which extended the Far::LimitStencilTableFactory to support face-varying and varying data.
The tests used to verify the compatibility of a provided StencilTable were corrected for the case of uniformly refined data to reflect the specified interpolation type (vertex, varying or face-varying).  The default case of vertex data was incorrect for uniform, so this fixes an existing regression (likely the cause of #1028).  When requesting limit stencils for varying data of a uniformly refined mesh, since a uniform PatchTable does not construct separate varying patches, the corresponding and equivalent vertex patches are used.  Additional and stricter error checking that had been added was also removed to preserve original …

Fix Far::LimitStencilTableFactory issues with uniform refinement

---

examples/glEvalLimit/glEvalLimit.cpp

Previously, the glEvalLimitViewer was hard coded to
use only adaptive refinement, but this change demostrates
how to evaluate patch locations on the linear patches
resulting from a uniform refinement.
By default, in a patch table created from a uniform refinement,
the patch indices for vertex patches account for base level indices,
while the patch indices for face-varying patches do not account for base
level indices.
This change also updates the example to set the patch table factory options
so that both kinds of patch indices account for base level indices.

Updated glEvalLimitViewer for uniform refinement

---

opensubdiv/far/ptexIndices.cpp

The existing ptex adjacency query was limited to only work for quads when written. This change extends it to include triangles.

Removed triangular restriction in Far Ptex adjacency query

---

opensubdiv/far/loopPatchBuilder.cpp

This change fixes slight cracks between the boundaries of triangular patches on either side of an inf-sharp dart edge.  The logic to compute the quartic point on the boundary between the two edge-points needed to be adjusted to consider the presence of darts (even though both corners may be regular) and not use the trivial assignment in that case.

Fix cracks between triangular Gregory patches at inf-sharp darts

---

opensubdiv/far/patchBasis.cpp
opensubdiv/osd/patchBasisCommon.h

The computation to adjust patch evaluation weights
for box spline triangle patches to account for boundaries
has been updated to use simple conditional logic instead
of index indirection tables. This results in better register
resource usage for some shader compiler implementations.
Previously, these methods could fail to compile on some
systems.

Minor changes to BoxSplineTri boundary computation

---

documentation/contributing.rst

- Removed explicit username and replaced it with generic example username.

Minor modification to the contribution docs.

---

README.md

- Split out the requirements for building docs into their own table
- Added missing dependency on graphviz

Update README for documentation build requirements

---

build_scripts/build_osd.py

This script is intended to make building OpenSubdiv with all its various options easier to manage.  It will automatically download and install the dependencies where it can (e.g., it can get GLEW automatically, but it can't get the CUDA SDK).
This is a fork of the similar script found in the USD repo.

Prototype build and install script for OpenSubdiv

---

build_scripts/build_osd.py

- Default the generator to Xcode on macOS
- Fix up how we pass in number of jobs so it works with Xcode

Fixes to the build script for macOS

---

examples/common/CMakeLists.txt
examples/common/argOptions.cpp
examples/common/argOptions.h
examples/common/shapeDesc.h
examples/common/viewerArgsUtils.cpp
examples/common/viewerArgsUtils.h
examples/glFVarViewer/glFVarViewer.cpp
examples/glFVarViewer/init_shapes.h
examples/glViewer/glViewer.cpp
examples/glViewer/init_shapes.h

Started refactoring how we parse arguments for sample viewer applications into a common place.  This will make it easier to keep args consistent between applications.

Factored viewer args parsing for into common place

---

examples/glFVarViewer/glFVarViewer.cpp

Changes here include several improvements to the glFVarViewer for inspecting face-varying interpolation and patches via UVs:
* added check-boxes for Control Edges and Control Vertices (common to other examples)
* added check-box for UV Backface Culling (defaults to Off so all UVs seen by default)
* relabelled the Boundaries pull-down to Linear Interpolation to reflect the enum it affects
Some of the source was additionally modified to avoid use of "boundary" to avoid confusion with the VtxBoundaryInterpolation option that is not affected.

Minor improvements to examples/glFVarViewer

---

opensubdiv/far/loopPatchBuilder.cpp

This change improves the shape of irregular patches for Loop when specifying the use of regular (Box-spline) patches rather than the Gregory triangles that enforce tangent continuity.

Improved regular patch approximations of irregular features for Loop

---

regression/far_perf/far_perf.cpp

Added a -spreadsheet option to far_perf which outputs
result data as comma separated values (CSV) which can
be imported directly into spreadsheet applications for
further analysis and charting.
Also, updated the other far_perf options to be more consistent
with the other tutorials and examples, e.g. when specifying
scheme types, refinement options, etc.

Updated far_perf output and options

---

examples/mtlViewer/mtlViewer.mm

Patches with transition edges were not being tessellated
correctly when drawing multiple patch types, e.g. with
Gregory or Legacy Gregory approximation at irregular features,
because the per-patch tess factors buffer was not being
offset correctly for the draw command for each patch type.
Fixed this to be consistent with other patch drawing by
recording and applying offsets when binding this buffer
for each patch type, and making sure that attributes for
the tess factors buffer are bound when drawing Legacy Gregory
patch types.

Fixed mtlViewer transition patch tessellation

---

documentation/intro.rst

Updated or removed stale links.

Fixed links to external documentation

---

azure-pipelines.yml

This commit adds initial Azure Pipelines CI support for OpenSubdiv.

Adding Azure Pipelines support for OSD
